### ISSUE TITLE
360 bridge tool issues

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/standard#100]
The 360 Brighe tool is referneced and links to a 404 from:
http://www.threesixtygiving.org/standard/reference/#toc-extending-the-summary-table

This was an old working title for what is now the [flatten-tool](https://github.com/OpenDataServices/flatten-tool), which has a useful implementation as part of [CoVE](https://github.com/OpenDataServices/cove)

The documentation should be rewritten to reflect this

**Comment by stevieflow** [comment]
@caprenter would you consider that changing this link to http://cove.opendataservices.coop/360/ would be a fix?

A wider issue might be that we may want cove to be at something like validator.threesixtygiving.org or something

However, this is a 404  / bug

(As an aside, would you consider this kind of link within the standard as different from a link within the schema: https://github.com/ThreeSixtyGiving/standard/issues/90#issuecomment-179905599 ?)

**Comment by caprenter** [comment]
I think changing the link is a fudge fix - The site also talks about the bridge tool in a couple of places, so really the tasks are:

Decide if we do want to point people to http://cove.opendataservices.coop/360/ (we might not if...)
Decide if we want to set up something like validator.threesixtygiving.org

Re-write the docs to reflect that there is a 'tool' that validates, converts, explores etc.

It is a 404, but putting a different link doesn't necessarily fix it.

(Aside - yes these are completely different issues. This is not in the schema)

**Comment by stevieflow** [comment]
Thanks @caprenter 

Agreed - Ill check in on this with 360

**Comment by stevieflow** [comment]
I think this issue can be closed.  The reference is now to "360 Data Quality Tool" and points to http://cove.opendataservices.coop/360/

In due course we can update this link to the new data quality URL.  But for now this specific ticket could be closed.  Agree @caprenter ?

**Comment by caprenter** [comment]
Yes. Thanks
