### ISSUE TITLE
Schema description for Currency is unclear

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#102]
http://www.threesixtygiving.org/standard/reference/

> The currency used in amounts. Use the three-digit currency code from ISO 4217

We've since an instance where people have used ``826`` instead of ``GBP`` - perhaps due to the term "three-digit" in the description text.

Perhaps we should add an example:

> The currency used in amounts. Use the three-digit currency code from ISO 4217.  eg: GBP

**Comment by stevieflow** [comment]
@caprenter I propose this is a documentation fix that can be made "now"?

**Comment by caprenter** [comment]
I'm guessing we do mean the "three-letter" code? The "three-digit" code would be a legitimate choice.

This is perhaps a more serious change than we think. If we're clear it's a bug, we should fix it as such. I think we should at least let publishers know.

"The currency used in amounts. Use the three-letter currency code from ISO 4217. eg: GBP"

**Comment by stevieflow** [comment]
We only had one publisher who used the three-digit code when preparing the data, which they changed 

CoVE / the schema doesnt like three-digit codes - the schema includes the three-letter codes (https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json) doesnt it?

Therefore, update documentation to 

> The currency used in amounts. Use the three-letter currency code from ISO 4217. eg: GBP

?

**Comment by caprenter** [comment]
Good points - I'll mark this as ready

**Comment by caprenter** [comment]
I'm happy this is done, but you might want to check

**Comment by stevieflow** [comment]
Great - https://github.com/ThreeSixtyGiving/standard/commit/e9d8c87155cd859fbe6e846afa8dc43d23861834 looks good
