### ISSUE TITLE
Org identifier guidance needs tweak/review

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#103]
I've observed instances where organisations have an internal, company and charity id for an organisation

The guidance at http://www.threesixtygiving.org/standard/identifiers/#toc-organisation-identifier does seem to place some emphasis on the company number, but we might want to review

Secondly, it is not 100% clear that the specific `Recipient Org:Identifier` field should contain, when there is more than one ID present.  EG: if we have the internal number in there, but also a charity number, do we replace?

There might need to be guidance and support about how publishers can best do this, too

This is based on working this with some publishers.  This page isn't a problem - but could benefit from a review

There's also a typo:

> you can stop use the given identifier

**Comment by stevieflow** [comment]
@caprenter the decision processes around this might best be dealt with through: https://github.com/ThreeSixtyGiving/standard/issues/13

However, fixing this typo could be undertaken "now" ?

**Comment by caprenter** [comment]
Splitting the typo into it's own issue: https://github.com/ThreeSixtyGiving/standard/issues/112
Removing the bug label here

**Comment by stevieflow** [comment]
I'm not sure this is now relevant - as we have an update via http://threesixtygiving-standard.readthedocs.io/en/revisions-for-usability/identifiers/ 

Agree @caprenter @timgdavies ?

**Comment by morchickit** [comment]
@timgdavies - can you please close if this is done?
