### ISSUE TITLE
Is currency a codelist we should publish and maintain?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#109]
The schema includes a list of values for currency:

> ```
> "enum": ["AED","AFN","ALL","AMD","ANG","AOA","ARS","AUD","AWG","AZN","BAM","BBD","BDT","BGN","BHD","BIF","BMD","BND","BOB","BRL","BSD","BTN","BWP","BYR","BZD","CAD","CDF","CHF","CLP","CNY","COP","CRC","CUC","CUP","CVE","CZK","DJF","DKK","DOP","DZD","EGP","ERN","ETB","EUR","FJD","FKP","GBP","GEL","GGP","GHS","GIP","GMD","GNF","GTQ","GYD","HKD","HNL","HRK","HTG","HUF","IDR","ILS","IMP","INR","IQD","IRR","ISK","JEP","JMD","JOD","JPY","KES","KGS","KHR","KMF","KPW","KRW","KWD","KYD","KZT","LAK","LBP","LKR","LRD","LSL","LTL","LVL","LYD","MAD","MDL","MGA","MKD","MMK","MNT","MOP","MRO","MUR","MVR","MWK","MXN","MYR","MZN","NAD","NGN","NIO","NOK","NPR","NZD","OMR","PAB","PEN","PGK","PHP","PKR","PLN","PYG","QAR","RON","RSD","RUB","RWF","SAR","SBD","SCR","SDG","SEK","SGD","SHP","SLL","SOS","SPL","SRD","STD","SVC","SYP","SZL","THB","TJS","TMT","TND","TOP","TRY","TTD","TVD","TWD","TZS","UAH","UGX","USD","UYU","UZS","VEF","VND","VUV","WST","XAF","XCD","XDR","XOF","XPF","YER","ZAR","ZMW","ZWD"],
> ```

Is this for ease of validation?  

We hardlink to wikipedia to explain more:

> [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)

But - we have no process to synch the schema with ISO 4217, so we cant be sure that these values are up to date.

It would be useful to clarify this 

Also referenced in https://github.com/ThreeSixtyGiving/standard/issues/90

**Comment by timgdavies** [comment]
This was for validation purposes. A process to sync with the ISO list could be useful.

**Comment by stevieflow** [comment]
Flagging for 0.9 as we should decide on the currecny (sic) of this codelist

@morchickit is also pulling this into the forum discussion on codelists #23

**Comment by morchickit** [comment]
See discussion here: https://forum.threesixtygiving.org/t/codelists-and-360giving-standard/20 
Keeping this issue open for now.

**Comment by morchickit** [comment]
@stevieflow - the Stewardship committee mention that CoVE does validates it , so can we check?

**Comment by stevieflow** [comment]
I tested this [sample file ](https://github.com/ThreeSixtyGiving/sample-data/blob/master/ExampleTrust-grants-fixed.xlsx)- and changed the currency value from ``GBP`` to ``GB``: 

https://dataquality.threesixtygiving.org/data/1f7eae0e-4db2-4c39-9c16-888042a1b122

![invalid](https://user-images.githubusercontent.com/1209944/33874349-565838bc-df16-11e7-9346-c0046ab3436c.png)

Therefore, it is true that the we validate against a codelist.  The oroginal question was how we would keep this up to date with the source list

@morchickit next step?

**Comment by Bjwebb** [comment]
BTW, here's how OCDS keeps this codelist in sync: https://github.com/open-contracting/standard/blob/1.1-dev/standard/schema/utils/fetch_currency_codelist.py

**Comment by stevieflow** [comment]
Thanks @Bjwebb - is that method something for 360 too?

**Comment by Bjwebb** [comment]
Yes, it can be.

**Comment by morchickit** [comment]
Ok, let's try it then!
I also saw this thread @stevieflow  https://discuss.iatistandard.org/t/tech-paper-codelist-management/538 is anything there useful for this case?

**Comment by stevieflow** [comment]
@morchickit the embedded/non-embedded codelist disucssion *may* be changing in IATI - see: https://discuss.iatistandard.org/t/redefine-selected-codelists-as-non-embedded-included-2-03/854/8

In terms of this particular currency list in 360, then:

- it is already within the schema
- it is used in validation

Therefore, I would suggest:

- The idea of a "list" in 360 is not contentious (this isn't grant themes or something)
- Ideally, we want to keep this in synch with the source list

Therefore, it seems like the code @Bjwebb suggests is something to schedule getting done.  The (much) wider discussion about codelist management could/should happen elsewhere.

Agree?

**Comment by morchickit** [comment]
Yes! Let's go with Ben's code then!

**Comment by stevieflow** [comment]
@Bjwebb internal ticket 12807

**Comment by stevieflow** [comment]
@Bjwebb actually - this is done: https://github.com/ThreeSixtyGiving/standard/pull/234 ?  This can be closed?
