### ISSUE TITLE
Flagging publisher / funding org location

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#110]
Some publishers/funding orgs may be based in countries other than the UK.

We could use the ``Funding Org: Country`` - but this may also be a string , and not using country codes for comparability

**Comment by caprenter** [comment]
The Location object is also available to Funding Org, so you can do as you suggest and supply a sting e.g. Norway, or you could use (in a spreadsheet) Funding Org:Location:Country Code and supply a code
