### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/standard#112]
From #103: 

On http://www.threesixtygiving.org/standard/identifiers/#toc-organisation-identifier

There's also a typo:

you can stop use the given identifier

**Comment by caprenter** [comment]
I'm happy this is done but you might want to check

**Comment by stevieflow** [comment]
Agree - https://github.com/ThreeSixtyGiving/standard/commit/bb618d247cb545133983238bf93f4c497ebce5e8 looks good.  Ill close this issue.  Thanks
