### ISSUE TITLE
Templates aren't linked to from the standard reference page

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/standard#116]
Reading http://www.threesixtygiving.org/standard/reference/ it isn't clear that I should be looking at http://www.threesixtygiving.org/standard/ instead to actually download the spreadsheet templates.

**Comment by caprenter** [comment]
Addressed in https://github.com/ThreeSixtyGiving/standard/commit/1899558e6c26caf582752a17ab1ffec325e66f74
