### ISSUE TITLE
360Giving sample data

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/standard#119]
As raised in https://github.com/OpenDataServices/cove/issues/84#issuecomment-153005562 this would be useful for Cove, and I suspect there's other uses for this.

@stevieflow Do you have any thoughts on how we might want to do this? We have some test data for Cove already, but it's very closely based on actual publishers data, which is probably undesirable for sample data that we actually link people to.

**Comment by stevieflow** [comment]
@Bjwebb are we thinking of an example file with actual values - albeit fictitious?

**Comment by Bjwebb** [comment]
Yes, much like open-contracting's fictional example sample data https://github.com/open-contracting/sample-data/tree/master/fictional-example

**Comment by stevieflow** [comment]
@Bjwebb @timgdavies @ekoner @caprenter @kindly is it a concern / relevance that the "fictional" example in OCDS names what seem to be "real" organisations and activities (eg: https://github.com/open-contracting/sample-data/blob/master/fictional-example/ocds-213czf-000-00001-01-planning.json - planning for a cycle path in Barnet)?

With IATI, I took care to make the example XML devoid of any real orgs/things: https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/activity-standard/activity-standard-example-annotated.xml

Any preference / thoughts?

**Comment by ekoner** [comment]
@stevieflow I refer fictional examples devoid of real orgs/things - using existing orgs, it may not be clear that the information is actually fictional.

**Comment by timgdavies** [comment]
Entirely fictional is preferable I think. If anyone wants to have a go at modifying the OCDS example to be more fictional that would be great.

**Comment by stevieflow** [comment]
I also found https://en.wikipedia.org/wiki/Example.com useful for this

**Comment by stevieflow** [comment]
[ExampleTrust-grants-fixed.xlsx](https://github.com/ThreeSixtyGiving/standard/files/640184/ExampleTrust-grants-fixed.xlsx)
[ExampleTrust-grants-broken.xlsx](https://github.com/ThreeSixtyGiving/standard/files/640185/ExampleTrust-grants-broken.xlsx)

I used these two files on a recent demo

**Comment by stevieflow** [comment]
Closing this, as we now have https://github.com/ThreeSixtyGiving/sample-data

**Comment by edugomez** [comment]
Reopening this as it is easier to modify data currently used in fixtures than using the sample data
