### ISSUE TITLE
Grants to individuals / organisations

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#120]
SORP asks:

> the total amount of grants paid analysed between grants to individuals and grants to institutions;

This would be very useful for 360 publishers.

A field to declare whether a grant was to an individual or organisation could then mean the `Recipient Org: Identifier` field may be redundant

**Comment by ekoner** [comment]
The Recipient Org: Identifier field allows distinguishing between several org with the same name e.g. St Mary's School example we discussed earlier. I agree that a mechanism to comply with SORP would be useful and considering how that impacts Recipient Org: Identifier.

**Comment by stevieflow** [comment]
Closing - as #18 talks about ``grantToIndividual``
