### ISSUE TITLE
Documentation includes Tooltips, which may not be easily viewed by some

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#124]
In https://raw.githubusercontent.com/ThreeSixtyGiving/standard/master/documentation/identifiers.md there are three extra pieces of guidance, described via a Tooltip class.

Over at http://www.threesixtygiving.org/standard/identifiers this causes a challenge - you can only "hover" over this guidance - it cannot be copied/grabbed/pointed to very easily

This doesnt seem to be a useful implementation of guidance.  Im unclear whether we need to edit the markup in the standard, or look at alternative ways to display this content in the website, or both

**Comment by ekoner** [comment]
Will this be resolved as part of the new documentation website?

**Comment by stevieflow** [comment]
Good point @ekoner 

@Bjwebb @caprenter ?

**Comment by caprenter** [comment]
This was resolved in https://github.com/ThreeSixtyGiving/standard/commit/f19f492f426690bc36ccbd8bc81c2218b0eff6c5 - the ticket was not closed at the time tho.
