### ISSUE TITLE
Actual Dates discrepancy

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/standard#125]
The Grants sheet page http://www.threesixtygiving.org/standard/reference/#toc-grants-sheet shows this text:

> Planned and actual dates of activity;

There is no further documentation of Actual Dates on the page unlike Planned Dates which includes of Planned Dates:Start Date, Planned Dates:End Date and Planned Dates:Duration (months)

I think this may be related to different configurations of actualDates and plannedDates in the json schema. Should actualDates include this line?

> "rollUp": ["startDate","endDate","duration"]

**Comment by timgdavies** [comment]
The reference to actual dates should be removed - as I think having both planned and actual in the default spreadsheet over-burdens it.

**Comment by caprenter** [comment]
This has been addressed in https://github.com/ThreeSixtyGiving/standard/commit/1899558e6c26caf582752a17ab1ffec325e66f74
