### ISSUE TITLE
Grant Programme - Missing description

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/standard#126]
In the JSON schema (http://www.threesixtygiving.org/wp-content/plugins/threesixty_docs/standard/schema/360-giving-schema.json), Grant Programme / grantProgramme is missing a description. 

> "description": "-"

This makes for awkward and incomplete documentation that's inconsistent with the rest of the standard:

> - An identifier for this grant programme.

Propose a description is added for Grant Programme.

**Comment by ekoner** [comment]
Additional fields with missing descriptions

- Actual Dates:Title
- Actual Dates:Description
- Actual Dates:Last modified

- Planned Dates:Title
- Planned Dates:Description
- Planned Dates:Last modified

- Funding Org:Contact Name
- Funding Org:Email
- Funding Org:Last modified

- Recipient Org:Contact Name
- Recipient Org:Email
- Recipient Org:Last modified

- Classifications:Last modified
- Funding Type:Last modified
- Grant Programme:Last modified

**Comment by ekoner** [comment]
For review https://github.com/ThreeSixtyGiving/standard/pull/141

**Comment by caprenter** [comment]
Closed by https://github.com/ThreeSixtyGiving/standard/pull/141
