### ISSUE TITLE
Dealing with publishers that cover multiple organisations - Publisher Name and ID suggestion

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/standard#127]
Based on schema.org and taking inspiration from the existing fields in the schema, I've come up with 2 potential extensions:

**Publisher:Identifier**
The identifer for the publisher this grant. Where the publisher is not the same organisation as the funder, it is important to provide this information to users of your data. This promotes trust and confidence in the data as well as providing an essential link to the provenance i.e. where the data came from. The Organisation Identifier Standard guidance explains how to create this ID, based either on the known company or charity number, or upon identifiers held in the grant-maker's internal systems.

**Publisher:Name**
The name of the publisher of this grant. When you provide a Publisher:Identifier, also provide a publisher name to show who the publisher of the grant. Where the publisher is not the same organisation as the funder, it is important to provide this information to users of your data. This promotes trust and confidence in the data as well as providing an essential link to the provenance i.e. where the data came from.

Advice to publishers could be to provide the above two and the data source.

**Comment by morchickit** [comment]
See forum topic- https://forum.threesixtygiving.org/t/dealing-with-publishers-that-cover-multiple-funders/24
