### ISSUE TITLE
Choose recipient org: identifier where an organisation is both a charity and a company, and for registered mutuals

### ISSUE THREAD

**Issue by prbass** [ThreeSixtyGiving/standard#13]
Summary:
We need some guidance on whether to prefer charity number or company number for recipient org: identifer.

I propose we prefer charity number.

Where a charity has both an England and Wales charity number, and a Scottish charity number, I propose we prefer the England and Wales charity number. 

We need some guidance on how to treat organisations on the Mutuals Public Register - I propose that we use the Companies House URI rather than creating a new IATI-organisation code.  

Detailed version: 

The 360giving standard adopts IATI organisational identifiers http://iatistandard.org/organisation-identifiers/ 

This is included in the standard as _recipient org:identifier_

A recipient organisation can be a charity and a company, and the same entity can be a charity in more than 1 jurisdiction e.g. Scotland and England and Wales. They can also have several subsidiaries, which can also be charities and/or companies. This diagram shows the corporate structure of Cancer Research UK, with each entity labelled with possible IATI standard identifiers. 
![sktrofq0jujnhk5egpqvbkw 1](https://cloud.githubusercontent.com/assets/2526376/3024692/4dbe7800-dffc-11e3-888f-ddd24a0efb6c.png)

In the data that has been published so far it is common for both charity number and company number to be recorded e.g. [Nominet](https://docs.google.com/spreadsheet/ccc?key=0An0cfq9yrA4NdGU5Q3doeHlZQldraTdGdWNwWER3NkE&usp=sharing), Big Lottery Fund.

There is currently no complete list linking charities to their associated companies. So including both fields in published data ought to be encouraged, even if it is not included in the standard.

We need some guidance on which register should take precedence. The IATI standard says: Registries that provide machine readable access to the data about organisations are generally preferred over those that do not (subject to (3) below)"

If we adopted this, we would prefer company number to charity number as things currently stand, because companies house has a URI schema and an API, while the Charity Commission EW, CCNI, and OSCR currently do not (although E&W available through opencharities, and an API is supposed to launch in next few weeks).

A further complexity arises because there are multiple charitable jurisdictions, but usually just one field called charity number. The jurisdiction can be deduced by the prefix

| Prefix | Jurisdiction | IATI organisation identifier prefix |
| --- | --- | --- |
| no prefix .i.e. starts with a number | England and Wales - Charity Commission | GB-CHC |
| SC | Scotland - OSCR (prefix often mistyped as sco because of leading zero in charity number) | GB-SC |
| NIC | Charity Commission Northern Ireland | GB-NIC |
| XN | HMRC number for organisations that aren't registered charities but are charities for tax purposes i.e. in Northern Ireland pre-2014 (there was no Charity Commission), and sports clubs (CASCs) | GB-REV |

I'm tempted to disobey the IATI guidance that would imply we should prefer company number to charity number as things stand, because if there is a charity number it makes explicit the fact that the recipient is a registered charity. This is information that will be pertinent to those grant makers whose policies are to only fund charities (e.g Lloyds Bank Foundation, Dulverton Trust), and there is also more information freely available e.g. full accounts for charities in England and Wales, financial information for charities in Scotland. 

**Therefore I propose to prefer charity number to company number where both are available.**

Where data has been published with both company numbers and charity numbers I suggest recommending coding to the IATI organisation standard using the following logic:

pseudo-code:

```
IF there is a charity_number
    IF it starts SC 
        THEN recipient org:identifier  is "GB-SC-" + charity_number
    ELSE IF it starts with NIC
        THEN recipient org:identifier is "GB-NIC-" + charity_number
    ELSE IF it starts with XN  
        THEN recipient org:identifier is "GB-REV-" + charity_number
    ELSE recipient org:identifier is  "GB-CHC-" + charity_number

ELSE IF there is a company number, recipient org:identifier is "GB-COH-" + charity_number

ELSE there is neither...

    recipient_org:identifier is "360G-" + funderid, + somenumber
        NB: These will need to be de-duped / cleaned
```

Example Excel / Google Sheets formula (charity numbers in Col A, company numbers in Col B)

```
=IF(LEFT(A2,3)="SCO","Check charity number",IF(LEFT(A2,2)="SC","GB-SC-"&A2,IF(LEFT(A2,3)="NIC","GB-NIC-"&A2,IF(LEFT(A2,2)="XN","GB-REV-"&A2,IF(ISBLANK(A2)=FALSE,"GB-CHC-"&A2, IF(ISBLANK(B2)=FALSE,"GB-COH-"&B2,"360G-org-nominettrust-"&ROW(C2)))))))

```

I'm not sure what to do in the case where the charity number contains numbers from both jurisdictions, e.g. if in some rows charity number is
"112345, SC04567" 

This applies if a charity is registered in England and Wales but also operates in Scotland (OSCR records cross-border charities main area of operation as "Outwith Scotland"). As I understand it, charities registered in Scotland can operate in England and Wales without being registered with the Charity Commission E&W. 

**For this reason, I'm tempted to suggest that the E&W charity number should be preferred in this instance.**

A related issue arises for organisations that are on the Public Mutuals Register. Most of these are Industrial and Provident Societies - a legal form popular with housing associations.

The mutuals are not compaines, but they are included in the Companies House URI schema, with the prefixes IP, SP,  NP, e.g. this Scottish Working Men's club. This gives us two potential alternatives - GB-MPR (not currently included in IATI code list) or GB-COH.

The companies house data is just a placeholder with name and number, while address details etc, are held on the Mutuals Public Register. 

GB-MPR-11WS
https://mutuals.fsa.gov.uk/SocietyDetails.aspx?Number=11&Suffix=WS

GB-COH-SP0011WS 
http://data.companieshouse.gov.uk/doc/company/SP0011WS 

**In this instance, I'd suggest preferring the Companies House URI and namespace.**

...But users of the data need to be aware that company numbers with these prefixes will not return the same amount of data from Companies House API as standard ones, but that some of this information is available elsewhere.

**Comment by timgdavies** [comment]
This links to wider work on Organisation ID guidance - but flagging to be addressed in next iteration of documentation work.

**Comment by stevieflow** [comment]
@timgdavies would you think http://threesixtygiving-standard.readthedocs.io/en/revisions-for-usability/identifiers/ means we can close this?

**Comment by timgdavies** [comment]
Yes.
