### ISSUE TITLE
geoType codelist source and documentation is no longer available

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#132]
The URLs on https://github.com/ThreeSixtyGiving/standard/blob/master/codelists/geoCodeType.csv are no longer valid...

**Comment by caprenter** [comment]
as statistics.data.gov.uk no-longer exists

**Comment by stevieflow** [comment]
An alternative, via DCLG: http://opendatacommunities.org/data/ons-geography-administration

**Comment by ekoner** [comment]
statistics.data.gov.uk is now back online https://twitter.com/DataGovUK/status/772775481720631296
