### ISSUE TITLE
geoType - code for a "local authority" area

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#133]
Our current code list doesnt seem to facilitate a code to describe a "local authority" area, as there appear to be different types - unitary, London, Metropolitan, Non-Metropolitan , and even County

Also evidenced in http://opendatacommunities.org/data/ons-geography-administration

**Comment by Bjwebb** [comment]
https://github.com/ThreeSixtyGiving/standard/blob/master/codelists/geoCodeType.csv has `CA` which is Council Area. Could that be what you're looking for?

**Comment by ekoner** [comment]
Prefixes  and maps to abbreviations are explained here: https://web.ons.gov.uk/ons/apiservice/how-to-guides

**Comment by ekoner** [comment]
#152 "Local Authorites" don't appear to exist as a single concept in the UK.

From The LGA quick guide to local government http://www.local.gov.uk/c/document_library/get_file?uuid=a5b2c920-8f40-4eae-9852-8b983724f5bc&groupId=10180

**England** has the most complicated structure:
1. County councils - cover the whole county and provide 80 per cent of services in these areas, including children’s services and adult social care)

2. District councils - covering a smaller area, providing more local services (such as housing, local planning, waste and  leisure but not children’s services or adult social care), can be called district, borough or city councils.

3. Unitary authorities - just one level of local government  responsible for all local services, can be called a council (eg Medway Council), a city council (eg Nottingham City Council) or borough council (eg Reading Borough Council)

4. London boroughs -  each of the 33 boroughs is a unitary authority, but the Greater London Authority (GLA) provides London-wide government, including special responsibility for police, fire, strategic planning and transport  

5. Metropolitan districts - effectively unitary authorities, the name being a relic from past organisational arrangements. They can be called metropolitan borough or city councils. 

All England ONS codes start with **E**

**Wales**
All 22 Welsh councils are unitary authorities providing all local government services to their local communities.

All Wales ONS codes start with **W**

**Scotland**
There are 32 Scottish unitaries and their powers are essentially the same as those of unitary authorities in England. 

Scotland has its own equivalent of ONS, http://www.gov.scot/Topics/Statistics. The code is **UA** and Scotland codes start with **S12**. The England equivalent is **E06** and in Wales **W06**.

For **Northern Ireland**, NISRA produced this guide http://www.ninis2.nisra.gov.uk/public/documents/NISRA%20Geography%20Fact%20Sheet.pdf

Northern Ireland is divided into 26 districts for local government purposes.  

NI codes are **LGD** (from 2014) and begin with **N09**

I think we could do with clarifying this in a blog / guidance post

**Comment by stevieflow** [comment]
Just pointing towards the DCLG Open Data Communities project, that makes a distinction between administrative geographies (described above by @ekoner) and then *organisations* that service these areas.  

The latter point might be useful when thinking about how authority organisations identify *themselves* , seperate to the geography they work in

http://opendatacommunities.org/def/concept/folders/themes/geography (the folder name "geography" may not help 100% though)


So: 
Manchester is an area E08000003 http://opendatacommunities.org/doc/geography/administration/md/E08000003 

Manchester City Council is an organisation:
http://opendatacommunities.org/doc/metropolitan-district-council/manchester (which could also be "identified" via the http://manchester.gov.uk domain)

Appreciate that this not central to the original point, but thought it useful and relevant

**Comment by stevieflow** [comment]
I want to link this issue to https://github.com/ThreeSixtyGiving/standard/issues/152

**Comment by ekoner** [comment]
GB-LAE is now the prefix for local authorities in England: https://github.com/OpenDataServices/org-ids/issues/67
GB-LAS proposed for Scotland: https://github.com/OpenDataServices/org-ids/issues/95
GB-PLA proposed for Wales: https://github.com/OpenDataServices/org-ids/issues/94

Related proposals: https://github.com/OpenDataServices/org-ids/issues/92

Closing this issue.
