### ISSUE TITLE
Currency description - unnecessary description?

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/standard#135]

**Comment by Bjwebb** [comment]
The issue here is that we have both https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L8 and https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L452

**Comment by caprenter** [comment]
Sorry, I thought I had documented that, but must have been half way through it or something. Thanks

**Comment by ekoner** [comment]
Update check-in: this was marked as ready, can we close this issue?
