### ISSUE TITLE
Identifiers for recipients that aren't charities or companies

### ISSUE THREAD

**Issue by prbass** [ThreeSixtyGiving/standard#14]
Write guidance on choosing identifers for organisations that do not have an obvious identifier / are not represented in the IATI Organisation register at present. 

Related to #13 

**Councils**
Follow GB-GOV-
So use domain name in gov.uk namespace - e.g. Belfast City Council www.belfastcity.gov.uk becomes GB-GOV-belfastcity

**Schools**
In the UK...
England and Wales - URN Number from Edubase: http://www.education.gov.uk/edubase/home.xhtml
(6 digits, numeric)
GB-DFE-

Scotland - SEED number from Education Scotland
http://www.educationscotland.gov.uk/scottishschoolsonline/ 
7 digits (numeric)
GB-ES-

Northern Ireland - 
DENI - Inst Ref number
7 digits (numeric)
GB-DENI-
Outside of the UK??

**Universities**
Complicated!

Universities in Wales are now registered charities, and have a charity number
so - GB-CHC-

Universities in Scotland are registered charities with OSCR so GB-SC-

**Universities in England.**
Some universities in England are registered charities for various historic, legal reasons  so will have a registered charity number. However the bulk are exempt charities, and not required to register, so will not have a charity number.

Their principal charity regulator is HEFCE (Higher Education Funding Council England), who maintain a list of the charity information for English universities here: http://www.hefce.ac.uk/whatwedo/reg/charityreg/highereducationinstitutionsascharities/charityinformationbyinstitution/ 

Some are incorporated by royal charter, and so will have a placeholder in the GB-COH namespace. 
Presumably some are also registered with HMRC, so may have an XN prefixed GB-REV- number (although I've not seen this quoted)

Lots of universities also have associated charities - for instance students unions are now registered charities, as are the independent colleges of Oxford and Cambridge.

Where no identifier is available - perhaps something following the GB-GOV pattern - using GB-UNI and the university's .ac.uk domain name - e.g. GB-UNI-anglia for Anglia Ruskin,GB-UNI-ox for Oxford.

A similar convention could work for international universities - e.g. Harvard US-UNI-harvard

Others not yet encountered...

**Health sector - NHS Bodies** - (I don't currently know anything about them!)
**Churches**
**non UK-registered organisations** - try to use the IATI organisation code-list when possible...

**Comment by stevieflow** [comment]
Universities: https://github.com/ThreeSixtyGiving/standard/issues/49

**Comment by stevieflow** [comment]
@timgdavies as per #13 - are we at a stage that http://threesixtygiving-standard.readthedocs.io/en/revisions-for-usability/identifiers/ satisfies this?

**Comment by timgdavies** [comment]
Yes.
