### ISSUE TITLE
Org identifier guidance - add note on educational bodies

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#146]
The IATI codelist includes GB-UKPRN 

Do we add a note to the Org ID guidance to point people to https://www.ukrlp.co.uk/ ?

@ekoner @Bjwebb

**Comment by Bjwebb** [comment]
Alternatively, are there better identifiers to be using for UK educational bodies? (and we could get that added to the IATI list)

**Comment by ekoner** [comment]
I'll review and write up some recommendations.

**Comment by ekoner** [comment]
Responsibility for educational establishments in the UK is devolved to:

- England & Wales
- Scotland
- Northern Ireland

The UK Register of Learning Providers is an attempt to "is a 'one-stop' portal to be used by government departments, agencies, learners, and employers to share key information about learning provider" but it is incomplete. Additionally, there is no mention that this data is openly licensed or available for bulk download. This could make the UKPRN undesirable for data users who want to reconcile education recipients. 

**My recommendations**
For England, use edubase (http://www.education.gov.uk/edubase/home.xhtml) which provides a URN for every educational establishment in England.

**Proposed prefix**: GB-EDU-
**Example**: GB-EDU-100000 - Sir John Cass's Foundation Primary School

For Wales, Edubase should cover this region, however, this FOI response makes it clear the Department of Education is only responsible for Engand (https://www.whatdotheyknow.com/request/list_of_all_schools_and_academie). This conflicts with the information on the edubase website, so my recommendation is to use edubase:

**Proposed prefix**: GB-EDU-
**Example**: GB-EDU-401277 - Pentrebach Infants School

Edubase also provide the UKPRN where available in their open data download (http://www.education.gov.uk/edubase/home.xhtml)

For  Northern Ireland and Scotland, there is no equivalent of edubase. In Scotland, there is list of schools, but this doesn't include universities or other learning institutions ( http://www.scotland.gov.uk/Topics/Statistics/Browse/School-Education/Datasets/contactdetails). I couldn't locate the equivalent of Scotland's school list in Norther Ireland, the link provided (http://www.deni.gov.uk/schools/index.htm) is broken.  

This lack of UK-wide information makes the UKPRN  the de-facto standard for education establishments in the devolved nations.

**Recommended prefix**: GB-UKPRN-
**Example**: GB-UKPRN-10050188 - Brimmond School

**Comment by ekoner** [comment]
Added writeup to https://github.com/ThreeSixtyGiving/standard/pull/148

**Comment by stevieflow** [comment]
One other thought - OfSTED number?
https://www.gov.uk/government/organisations/ofsted

**Comment by ekoner** [comment]
@stevieflow OFSTED only cover schools and institutions for young people, so Universities would not be included.

**Comment by caprenter** [comment]
GB-EDU is now on the IATI list.
http://iatistandard.org/201/codelists/OrganisationRegistrationAgency/
