### ISSUE TITLE
Charity and Company Number in roll-up properties

### ISSUE THREAD

**Issue by martinburchell** [ThreeSixtyGiving/standard#15]
We think it would be useful to add the charityNumber and companyNumber properties to the list of rolled up Activity table properties as they are sometimes included in lists of grants.

**Comment by practicalparticipation** [comment]
This is done in the latest JSON version of the schema. Will be in 1.0 release due around March

**Comment by stevieflow** [comment]
One question - would FSA identifiers also be feasible identifiers?  Macc - for example - refer to some organisations that are FSA registered (as in, cooperatives)

**Comment by practicalparticipation** [comment]
Right now there is some redundancy built in around organisation identifiers - as in Charity Number and Company Number are explicit properties, but other organisation types can also be identified using the Organisational ID convention in the Recipient Org: ID column. 

Would that work?
