### ISSUE TITLE
Transaction values are integers

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/standard#150]
In the rest of the schema, most values are 'numbers' in the schema, but in transactions the values are set as integers.
https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L33

Is this intentional or does it need to change?

**Comment by timgdavies** [comment]
This sounds like a bug to me.

**Comment by caprenter** [comment]
@Bjwebb - can you take a look at this at some point to just see if there are any major implications

**Comment by Bjwebb** [comment]
From http://json-schema.org/latest/json-schema-core.html#anchor8 this is "Any JSON number. Number includes integer.", so the change would be backwards compatible.

So, I think we should make this change.

**Comment by drkane** [comment]
I had also noticed this, changing makes sense. I haven't seen any transaction records in the wild so presumably would not have a huge impact on existing data.

**Comment by BobHarper1** [comment]
We had this as an issue in the Autumn 2017 Bug Fix, but in fact it's already part of the schema.

**Comment by BobHarper1** [comment]
We can close this then, it was fixed way back in June '17!
