### ISSUE TITLE
Guidance for identifying Local Authorities

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/standard#152]
How to identify Local Authorities? Which identifier should be provided?

**Background:**
Local Authorities are missing from the IATI lists which cover:
- UK  Government Departments, Agencies & Public Bodies
- UK Government Departments Reference Numbers

**Registrar?**
Department for Communities and Local Government (DCLG) may be the best starting point for a list of all UK Local Authorities.

**Comment by ekoner** [comment]
**Linked Open Data**
http://opendatacommunities.org/ is the UK Department for Communities and Local Government's official Linked Open Data website.

It provides a selection of statistics on a variety of themes including Local Government finance, housing and homelessness, wellbeing, deprivation, and the department's business plan as well as supporting geographical data.

**Comment by ekoner** [comment]
DCLG and LGInform both advocate for use of the council uri as the organisation code. This is used by Leeds City Council - see http://leedsdatamill.org/dataset/council-spending/resource/406e9b94-29fd-4d02-ad91-a1fcb558e776#

For example: http://opendatacommunities.org/id/metropolitan-district-council/leeds

**LGInform**
Organisation code: A unique code to identify the spending organisation. For LAs this can be the URI from Open Data Communities.
http://validator.opendata.esd.org.uk/spend

**Comment by stevieflow** [comment]
--> @jamie-whyte

**Comment by MikeThacker1** [comment]
Yes, LGA / LG Inform guidance is to use URIs (uniform resource identifiers) to identify:

- English local authorities at http://opendatacommunities.org  
- Official geographies (including the areas that local authorities govern) at http://statistics.data.gov.uk/ (which is currently down)
- Other geographies (and official ones while the above site is down) at http://neighbourhoods.esd.org.uk/

[This URI search tool](http://uris.opendata.esd.org.uk/) will find specific links.

So here are [Local authorities in England](http://opendatacommunities.org/data/local-authorities).

Here are [UK Local Authority areas](http://neighbourhoods.esd.org.uk/#?areaType=LA&tab=Map).  [The area type details tab](http://neighbourhoods.esd.org.uk/#?areaType=LA&tab=ViewAreaType) has a CSV download.

**Comment by caprenter** [comment]
There are two issues here:

1) Which 'registration aganecy' do we use to talk about local authorities? (in the context of 'organisation identifiers' - note that we can talk about them as 'locations' by specifying a geographic code type and then then a code from that specific list). The suggestion here is to use http://opendatacommunities.org - there may or may not be a better alternative.

2) The second issue is, given that we have established a source of unique identifiers for local authorities, how do we use them in the standard?
The current guidance: http://www.threesixtygiving.org/standard/identifiers/#toc-organisation-identifier tells us that we should use a prefix and then the identifier.

This prefix should preferably come from the [IATI Organisation Registration Codelist](http://iatistandard.org/codelists/OrganisationRegistrationAgency/) and if not the guidance says

"If the prefix you need is not listed, contact the support team.
If you do not have any external registration numbers for the organisation, use your 360Giving prefix and any internal identifier you have for this organisation."

As the IATI list does not have http://opendatacommunities.org as a recognised registration agency, if we were agreed to use it, we would need to get that onto their list. (IATI may not want it on their list, in which case we might need to have our own list, or a fork of theirs or something)
As there is nothing on the IATI list we can use our own 360Giving prefix, so right now I could use:
360G-myorg-http://opendatacommunities.org/id/metropolitan-district-council/leeds

Obviously that then becomes difficult to use as a unique identifier across combined data.

What about using just a URI and no prefix?
This is problematic because a data user doesn't know what to expect from the URI it finds. The prefix-identifier approach tells a data user - go to this list, find this identifier. A URI just says go here.
That may or may not be a problem. Consuming applications could look for a prefix OR a http. Is that acceptable and easy to use?

**Comment by ekoner** [comment]
While we work through to a definitive answer, I've asked ONS about SNAC Codes. These are used by direct.gov.uk to provide a list of local authorities http://local.direct.gov.uk/Data/local_authority_contact_details.csv - it appears that SNAC Codes are deprecated however.

**Comment by ekoner** [comment]
Also relevant from #14

**Comment by ekoner** [comment]
> 1) Which 'registration aganecy' do we use to talk about local authorities? (in the context of 'organisation identifiers' - note that we can talk about them as 'locations' by specifying a geographic code type and then then a code from that specific list). The suggestion here is to use http://opendatacommunities.org - there may or may not be a better alternative.

There is currently no better alternative - we are waiting on some work from GDS looking at registers but that is in alpha.

> 2) The second issue is, given that we have established a source of unique identifiers for local authorities, how do we use them in the standard?
> The current guidance: http://www.threesixtygiving.org/standard/identifiers/#toc-organisation-identifier tells us that we should use a prefix and then the identifier.

The proposal should make this moot, as it uses an established IATI identifier.

**Comment by caprenter** [comment]
If you want to use GB-GOVUK - you need to use the rules set out by IATI. 
From: http://iatistandard.org/202/codelists/OrganisationRegistrationAgency/

GB-GOVUK
UK Government Departments, Agencies & Public Bodies
Use the final segment of the url (below /organisations) as the “registration number”, converting all “-” to “_”. Keep “registration number” portion all lowercase. 
GB
https://www.gov.uk/government/organisations

So I can reference the Attorney General's Office: https://www.gov.uk/government/organisations/attorney-generals-office
as
GB-GOVUK-attorney_generals_office

Crucially, you can only use items from the https://www.gov.uk/government/organisations list, so...

I can't use GB-GOVUK to reference things that are NOT on their list, such as Belfast City Council
i.e. GB-GOVUK-belfastcity should allow me to look up https://www.gov.uk/government/organisations/belfastcity which is Page not Found.

**Comment by timgdavies** [comment]
I've been investigating a couple of options here.

As David notes, GB-GOVUK can only be used for resolve-able URLS on gov.uk, and isn't an ideal option even then, as it doesn't guarantee it is picking out unique organisations.

I've been looking at the [EU NUTS Local Administrative Units](http://ec.europa.eu/eurostat/web/nuts/local-administrative-units) tables as one possible source of identifiers, but these have some complexities as:

* Whilst they [*prefer* administrative units](http://ec.europa.eu/eurostat/web/nuts/principles-and-characteristics) there is no guarantee that a NUTS code equates to a legal entity such as a local authority. 
* The lookup lists at http://ec.europa.eu/eurostat/web/nuts/local-administrative-units are quite confusing (although they do appear to be kept reasonably up-to-date and with change log noted)

I'll keep exploring.

Through the Organisation Identifiers project we are working on we do essentially have a forked version of the IATI Org Registration codelist for the next few months that we can add to, and merge back into the IATI list later in the year providing we follow good practices developing the forked list.

**Comment by timgdavies** [comment]
It does appear that all the services we might reasonably use from the UK Government to provide anything authoritative are offline or limited in the information they provide/how stable they might prove to be.

For that reason, I'm leaning back towards the NUTs codes. Eurostat do appear to maintain these, and they are derived from national lists in some form.

I've started documenting how 'XR-NUTS' could work as a prefix at https://airtable.com/shrsKz1Tb7wVE8Vx9/tblAPFyWmOBCJeiCU/viwRKM4Vghgfupcfb/rec8rvrN7aOJJ0Ir8

But I'm still struggling to find a good list for LAU1 (the level of NUTs which actually has Local Authorities in) - as the mapping they provide is just for LAU2 -> NUTS3

**Comment by Julianlstar** [comment]
Hi Julian here. Steven pointed me to this discussion as these are exactly the same questions that I have been asking.
I will be running some 360Giving workshops with local authorities in a couple of weeks time.
In September last year UK Gov released their Local Authority England Alpha Register [http://local-authority-eng.alpha.openregister.org](url) updated 24/2/17 with each local authority having its own Alpha3 code. One would assume that this would be a maintained registry although it is in Alpha and only covers England.
As far as Eurostat identifiers are concerned NUTS3 is too broad - Greater Manchester is covered by 5 NUTS3 identifiers but these don't map on to the 10 administrative boroughs whereas LAU1 does as you say Tim. It looks like these will persist until 2018 but whether UK identifiers will be maintained by Eurostat post-Brexit is unclear.
URIs as identifiers look inelegant and multidimensional- am afraid that is all I can offer on that one.
If adopting the UK Gov LA England Alpha3 code for local authorities does that mean that you would be following the convention of GB-GOVUK-MAN for Manchester City Council GB-GOVUK-SLF for Salford City Council etc.
What is the perceived wisdom on this? Is the Scotland, Wales and Northern Ireland creating their own Registry of local authorities?

**Comment by ekoner** [comment]
Hi @Julianlstar 

Here's the latest guidance:

Local authority identifiers will now be based on the [Local authority England alpha register](https://data.blog.gov.uk/2016/09/07/local-authority-england-alpha-register/). We believe this is stable and will be supported long-term. We are also shifting to using the Org-id project prefixes rather than the IATI agency register as part of the Joined Up Alliance project.

The prefix for this register is: GB-LAE. Using the 3 letter codes from the register would give an organisation identifier of 

- Birmingham City Council (BIR): GB-LAE-BIR
- Manchester City Council (MAN): GB-LAE-MAN
- Salford City Council (SAL): GB-LAE-SAL

Follow [UK Alpha Registers: Local Authorities (England), Government Organisations](https://github.com/OpenDataServices/org-ids/issues/67) for more on implementing this in the Org-id project and in CoVE.

**Comment by stevieflow** [comment]
Thanks @ekoner 

We should make plans for this to be in the standard - eg

http://www.threesixtygiving.org/standard/identifiers/#toc-organisation-identifier
http://www.threesixtygiving.org/support/guidance/identifying-schools-universities-and-other-educational-establishments/

**Comment by ekoner** [comment]
@stevieflow On my to-do list, still some background work to be done in the org-id project and on CoVE. I'll take another look in May.

**Comment by Julianlstar** [comment]
@ekoner @stevieflow Brilliant stuff. Just to confirm that Salford would be GB-LAE-SLF.
How the devolved authorities will be accommodated into this standard is unclear. I would assume that like Greater London GB-LAE-GLA Greater Manchester will have a new identifier - to be honest I am surprised it doesn't exist already.

**Comment by ekoner** [comment]
@Julianlstar These things are sent to try us :)

**Comment by ekoner** [comment]
Documentation updated on new site. Public register proposal submitted for Wales and Scotland. Closing this issue as resolved.
