### ISSUE TITLE
Clarify links between 360Giving organisation prefixes and IATI

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/standard#156]
It isn't terribly clear in the Organisational Identifiers page here - http://www.threesixtygiving.org/standard/identifiers/#organisation-identifier that 360Giving relies on the IATI Organisation Registration Agency codelist and why - http://iatistandard.org/201/codelists/OrganisationRegistrationAgency/

Propose we add an explanation about the relationship and what it means to publishers to the Organisational Identifiers page.

**Comment by ekoner** [comment]
Scheduled for go-live 04-Aug-2016

**Comment by caprenter** [comment]
This is now live
