### ISSUE TITLE
Consider a field for Beneficiary Location: Scope

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#165]
Whilst describing the specific geographic area(s) that a grant benefits is very useful, some additional data might help classify and help users understand the scope to which this grant applies. 

For example:
- International - a grant applicable to the world / global
- National - a grant applicable to a whole country
- Regional - a sub region of a country (eg London in UK context)
- District - (local authority in UK context) 
- Local - (ward level)

A focus would be to properly describe the above (proposed) codes, without slipping into UK specifics

IATI has something similar, arguable more complex: http://iatistandard.org/202/codelists/ActivityScope/

Additionally, this also implies the addition of a code list

**Comment by mlenczner** [comment]
Hi all,

Just a note that our client / partner expressed a need for this field last
week. And beyond that, we see it as important for our context.

Michael Lenczner
Director of Powered by Data <http://www.poweredbydata.org/>, a Tides Canada
Initiative | CEO of Ajah <http://www.ajah.ca/>
+1-514-708-5112

**Comment by BobHarper1** [comment]
Similarly, Organizations (both funders and recipients) have remits along similar lines, but for a particular grant, their beneficiaries don't always match the remit, eg:  

* my org works regionally, but we've also run projects that are local in scope  
* a community group is local, but might participate in a regional programme  
* Oxfam is international, but might fund on a national or sub-national basis   

Would this merit another additional field, for Organization:Scope, to add more context?

**Comment by morchickit** [comment]
See forum thread here: https://forum.threesixtygiving.org/t/new-field-beneficiary-location-scope/25
