### ISSUE TITLE
Consider using MetaTab

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/standard#172]
Should 360Giving spreadsheets have a MetaTab? http://metatab.org/

**Comment by ekoner** [comment]
I'll review and write up my findings.

**Comment by stevieflow** [comment]
I think we have some investigation around this in terms of IATI and CoVE - correct @Bjwebb ?

**Comment by Bjwebb** [comment]
Yes, we've added support for a metadata tab - https://flatten-tool.readthedocs.io/en/latest/unflatten/#metadata-tab
It has some subtle differences to the metatab spec, to maintain consistency with other bits of flatten-tool.

We're currently working on adding support to CoVE - https://github.com/OpenDataServices/cove/issues/641. This is useful for IATI, but we're also doing it to support OCDS PPP in CoVE.

**Comment by stevieflow** [comment]
Great, thanks @Bjwebb 

@timgdavies @ekoner does this specific issue need to remain open?

**Comment by ekoner** [comment]
Closing.
