### ISSUE TITLE
Clarify how to properly format organisation identifiers

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/standard#173]
The documentation for [organisation identifiers](http://www.threesixtygiving.org/standard/identifiers/#toc-organisation-identifier) isn't explicit about how company numbers (and other identifiers) should be formatted.

I've added some guidance but it would be useful to add a worked example to this section. Related to #121

**Comment by timgdavies** [comment]
Hopefully we can draw on the guidance you develop here in the Org ID project too. Let's try and touch base on that soon.

**Comment by ekoner** [comment]
I've added some guidance to the Identifiers page which is pending go-live: 

> Tip: Companies House use an 8 digit number, so always provide the leading 0 where needed. For example GB-COH-03416658.
