### ISSUE TITLE
Licensing info - inconsistent

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#177]
from @julianlstar via @KDuerden

http://www.threesixtygiving.org/standard/licensing/#toc-is-there-an-example

> Finally, anything shared or adapted has to be licensed as CC BY 4.0.

@Bjwebb states: that sentence just wants removing in its entirety

**Comment by Julianlstar** [comment]
Brilliant stuff

J

Julian Tait   Co-founder, The Garden
☎︎	+44 7802 851 394	✉︎	julian@thegarden.io <mailto:julian@thegarden.io>	⌖	Manchester, UK
⎈	thegarden.io <http://thegarden.io/>	⣗	@thegardenio <http://twitter.com/thegardenio>	㏇	UK Reg. 9279317 | VAT 232 1284 45

**Comment by caprenter** [comment]
This should be fixed now. Please review: 
http://www.threesixtygiving.org/standard/licensing/#toc-which-license-should-you-choose-

Closing. Please re-open if more attention needed.
