### ISSUE TITLE
Grants without recipient organisations - for listing groups of individual grants

### ISSUE THREAD

**Issue by prbass** [ThreeSixtyGiving/standard#18]
Feature request from Paul Hamlyn Foundation - they want to be able to include information about grants they have made but where the individual recipients are not disclosed for data protection reasons etc. 

These are the example rows - won't include them in the files I upload for now, but they are in the published file at: http://www.phf.org.uk/news.asp?id=2237

| Recipient Org: Name | Classification: Grant Programme | Classification: Grant Fund | Title | Currency | Total Amount awarded |
| --- | --- | --- | --- | --- | --- |
| Awards to eight individuals/organisation through Breakthrough Fund | Arts | Breakthrough Fund 2013 | Breakthrough Fund 2013 | GBP | 1811000.00 |
| Awards to Individual Composers | Arts | Awards for Artists 2013 | Awards for Composers - to three composers | GBP | 150000.00 |
| Awards to Individual Visual Artists | Arts | Awards for Artists | 2013 Awards for Visual Artists - to five individuals | GBP | 250000.00 |

**Comment by practicalparticipation** [comment]
To be addressed in documentation.

**Comment by timgdavies** [comment]
The issue of being able to explicitly identify grants to individuals has also come up as a result of looking at SORP guidance, where a charity may wish to report on the breakdown of:

- Grants to individuals
- Grants to institutions

At the moment the CSV and JSON models explicitly refer to **Recipient Organisation**, and not just to **Recipient**, so saying that 'individuals' could just be put in the Organisation section would be problematic.

There are also data protection issues with respect to individuals (as noted in the original comment), such that the standard may want to discourage publishing individuals details.

## Proposal 

* We should add a boolean field to the standard for ```grantToIndividual``` which should appear just before the Organization rows. 

In addition:

* The validator should include warnings when Organization identification information is present when the ```grantToIndividual``` flag is set

**Comment by caprenter** [comment]
We should be aware the pull https://github.com/ThreeSixtyGiving/standard/pull/147 made recipient orgs required. This make sense for the vast majority of grants (we think) and leads to a better user experience around validation.

We do need to take this case into account tho

**Comment by mlenczner** [comment]
Already our federal arts funder is publishing grants made to both orgs and
individuals. They display different info for each in the name of personal
privacy.

On Wednesday, 1 June 2016, caprenter <notifications@github.com> wrote:

> We should be aware the pull #147
> <https://github.com/ThreeSixtyGiving/standard/pull/147> made recipient
> orgs required. This make sense for the vast majority of grants (we think)
> and leads to a better user experience around validation.
>
> We do need to take this case into account tho
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/18#issuecomment-222949125>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKna0Q3DOXM-riF7tbF3p9RsKjJsx1Gks5qHVlQgaJpZM4CQAqs>
> .
>


-- 
Michael Lenczner
Director of Powered by Data <http://www.poweredbydata.org/>, a Tides Canada
Initiative | CEO of Ajah <http://www.ajah.ca/>
+1-514-708-5112

**Comment by caprenter** [comment]
Just a note that current documentation does tell us how to deal with this situation:
http://www.threesixtygiving.org/standard/identifiers/#toc-organisation-identifier

Is the proposal for `grantToIndividual` still wanted?

**Comment by stevieflow** [comment]
@timgdavies are you thinking ``grantToIndividual`` is still something to pursue in the schema?

Elsewhere, we have a couple of documentation pieces that talk about this - there is a need to rationalise

But first of all then we just clarify ``grantToIndividual``

**Comment by timgdavies** [comment]
I think `grantToIndividuals` still has value as both a substantive field for analysis (supporting SORP reporting), and to assist us in providing more privacy-protecting tools (we can warn when there are `grantsToIndividuals` in a dataset, and double-confirm during data quality tool process whether the user has properly removed any information they should have kept out of the data.

**Comment by stevieflow** [comment]
Ok thanks @timgdavies 

@morchickit did you plan some wider discussion on this in the forum?

**Comment by mlenczner** [comment]
On Mon, Sep 11, 2017 at 10:49 AM, Tim Davies <notifications@github.com>
wrote:

> I think grantToIndividuals still has value as both a substantive field
> for analysis
>
+1

Several of our partners are already publish grants to individuals. Please
feel free to ask us directly if you have use cases for which you want
feedback.

 Mike

**Comment by BobHarper1** [comment]
Just flagging a comment from @jacklord on https://github.com/OpenDataServices/social-finance-data-spec/issues/13#issuecomment-338030548 provides a potential solution in having a `recipient` field with a `oneOf` for either `recipientOrganization` (as it currently is) or `recipientIndividual` (a new schema).

**Comment by stevieflow** [comment]
Ive removing this from the version 1 project

**Comment by mariongalley** [comment]
I think this is fixed by the ability to declare grants to individuals in the 360Giving Data Standard #339 

Happy to close @KDuerden ?
