### ISSUE TITLE
Updating the links to CoVE

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#181]
In the resources we use to generate the documentation, please can we change the link to the Data Quality Tool to be https://dataquality.threesixtygiving.org/

**Comment by caprenter** [comment]
grep -rnw . -e 'cove.opendataservices' returns:

./.ve/src/flattentool/README.md:388:You can also upload the file to http://cove.opendataservices.coop/360
./documentation/reference.md:21:The [360Giving Data Quality Tool](http://cove.opendataservices.coop/360/) can be used to convert data between these formats, providing structured data for developers, and spreadsheet simplicity if you want to browse, sort and filter data on your desktop. 
./documentation/reference.md:441:The [360Giving Data Quality Tool](http://cove.opendataservices.coop/360/) supports round-tripping of data between the Spreadsheet Template and JSON representations. 
./documentation/src/reference.md:21:The [360Giving Data Quality Tool](http://cove.opendataservices.coop/360/) can be used to convert data between these formats, providing structured data for developers, and spreadsheet simplicity if you want to browse, sort and filter data on your desktop. 
./documentation/src/reference.md:239:The [360Giving Data Quality Tool](http://cove.opendataservices.coop/360/) supports round-tripping of data between the Spreadsheet Template and JSON representations.

**Comment by caprenter** [comment]
This has been merged in the docs, so master represents the most up to date version.
Also this has been deployed to the 360Giving website
