### ISSUE TITLE
Identifiers containing slashes

### ISSUE THREAD

**Issue by qris** [ThreeSixtyGiving/standard#19]
We've been assuming that identifiers don't contain slashes, so that we can use them in URLs, but actually Wellcome activity IDs and HMRC unregistered identifiers such as XN/3223 do contain slashes. What characters are allowed in an identifier, and how long can it be?

**Comment by timgdavies** [comment]
The [grant identifier guidance](http://www.threesixtygiving.org/standard/identifiers/#toc-grant-identifier) makes a recommendation on this, but does not mandate any replacement pattern. 

This approach appears to be working, so closing this issue for now.
