### ISSUE TITLE
Make funding Type a mandatory field

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/standard#196]
This came up also in out Dr. Data workshop, but here is the email feedback we got from user: 
Suggestion: Grant givers should state whether the grant is endowment, restricted or unrestricted.
Backstory: some organisations don't respect these definitions, which can lead to breaches of trust. It is truly toe-curling when you discover this sort of thing in an otherwise "right-on" organisation.  If we want transparency and money to be spent as intended, this is an essential thing to include.  (Without meaning to bog anyone down in technicalities, here is some guidance which strictly speaking applies to charities, but frankly, if a non-charitable Ltd Co got a grant, the same definitions might apply: http://www.charitysorp.org/media/620724/frs102_module-2.pdf Trust me, its v user-friendly...)

@stevieflow  - we can discuss this when we are looking at this repo next week

**Comment by timgdavies** [comment]
I'm starting to collect a library of key questions that we can ask for each requested update that comes in for the standard, to help make more explicit the tacit process we've had to date. 

Here's a quick sketch of questions to ask when we're considering **Should we have this field in the standard? *Or* should it be mandatory?**

(1) Is this something that a large number of data providers already have in, or can infer from, their existing data in some form? How much would providers have to change to be able to provide this field? 

(2) Is there a clear use-case for the data? What will become possible when there is standardised data for this field? How compelling is the impact? 

(3) Is this field useful if only **some** users of the data standard provide it? Or does it need to be provided by **almost everyone** to become useful?

(4) Are there existing reporting requirements that relate to this field that *providers* have to work with?


I don't know the answer to these questions for 'restricted funding' fields, though I'm encouraged by the SORP guidance that, if people were encouraged (using data quality tool feedback) or required (by a mandatory field) to provide this, then there a fairly clear set of definitions to defer to for mapping to a codelist for this field.

**Comment by morchickit** [comment]
Moved this to the forum to the respected thread - https://forum.threesixtygiving.org/t/award-type-field/21/3
