### ISSUE TITLE
Data providers could state whether the grant represents a form of "State Aid"

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/standard#197]
This also came from a publisher feedback - 

Backstory: This cropped up at a Big Society Capital event I went to last week.  I know we only have two years before we leave the EU (ish....), but when money comes from Local/National Govt it is quite possibly EU money!!!  Many organisations get money form all over the place, so it can be hard to keep track what was state aid and what was not (N.B.: Lottery money is apparently NOT State Aid...).  On some occasions (e.g. when applying for a govt grant or seeing whether they can offer Social Investment Tax Relief to potential investors in a project), these recipients need to declare that they have exceeded State Aid thresholds.  Many recipients don't have the first clue if the £££ they received was State Aid or not (the donor is supposed to tell them...), but unfortunately, sometimes councils don't know themselves!  Still, as with the above suggestion, simply prompting people to consider this would be a good hygiene exercise.

**Comment by timgdavies** [comment]
To use the same questions as in #196:

(1) Is this something that a large number of data providers already have in, or can infer from, their existing data in some form? How much would providers have to change to be able to provide this field? 

(2) Is there a clear use-case for the data? What will become possible when there is standardised data for this field? How compelling is the impact? 

(3) Is this field useful if only **some** users of the data standard provide it? Or does it need to be provided by **almost everyone** to become useful?

(4) Are there existing reporting requirements that relate to this field that *providers* have to work with?

**Comment by morchickit** [comment]
Moved to forum https://forum.threesixtygiving.org/t/specify-state-aid/191
