### ISSUE TITLE
Accommodating crowdsourced giving into the standard

### ISSUE THREAD

**Issue by Julianlstar** [ThreeSixtyGiving/standard#200]
We have been working with the Coop Group to enable them to release their Local Community Giving Fund data. This fund gives approximately £18 million per annum. There are a number of categories where the funding model doesn't map perfectly. These are to do with award dates and disbursements.

- People apply to have their project supported at the point of application they are asked for an idea of how much money is required for the project - I have mapped this to **Amount Applied For** 

- A decision is made on a date to allow the applicant to be highlighted as a local cause that members can support. As this is for all intents and purposes a funding decision I have mapped this to **Award Date**

- The crowdfunding element is then allowed to run for a number of months and at a certain point an amount will get paid on a date - I have mapped this to **Disbursement Transaction:Transaction Date**

- The fund per cause will have reached a certain amount and this will get paid - I have mapped this to **Amount Awarded**

I am not sure at the moment if the causes get more money than they say the project will cost. Is the mapping correct?

**Comment by Julianlstar** [comment]
This has been resolved in the Coop Groups case by them making the decision that the Award Date is the point in which the fund stops taking money and releases the funds.

**Comment by morchickit** [comment]
Topic is now here: https://forum.threesixtygiving.org/t/accommodating-crowdsource/192
