### ISSUE TITLE
New closed government register?

### ISSUE THREAD

**Issue by Julianlstar** [ThreeSixtyGiving/standard#201]
I have been looking through the data in the Coop Local Community Fund and there are some XT numbers in there.

XT numbers are created by HMRC when charitable organisations register with them [https://www.gov.uk/charity-recognition-hmrc](url) It looks like you can apply for an XT number even if you are not a charity as long as you supply them with Mem and Arts.

The problem with this is there doesn't seem to be an open register of these organisations. Do we just ignore it?

**Comment by timgdavies** [comment]
We have the suggested code [GB-REV](http://org-id.guide/list/GB-REV) for these, keeping the XC prefix or XT prefix.
