### ISSUE TITLE
CAF Beneficiary  Numbers

### ISSUE THREAD

**Issue by Julianlstar** [ThreeSixtyGiving/standard#205]
Working with Coop Group to release their grants to the 360Giving standard, came across CAF Beneficiary Numbers. All the applicants had one which made me think that Coop was registering them with CAF as part of their due diligence.

Can't seem to see any reference to them on the internet though.

**Comment by timgdavies** [comment]
I've just been exploring the CAF charity search and cannot find any reference to these either.

We could ask CAF and look to get a list included in org-id.guide if it is public (or can be public), but it might be useful to confirm first whether there are any other identifiers for the organisations that could be used instead (e.g. can these beneficiary numbers be mapped to charity numbers instead?)

**Comment by Julianlstar** [comment]
I have asked for clarification as to how or why these are used.

**Comment by morchickit** [comment]
We are speaking about these, right? https://www.cafonline.org/my-personal-giving/plan-your-giving/individual-giving-account/how-does-it-work

**Comment by Julianlstar** [comment]
@morchickit You may be on to something and I am still trying to get a response from Coop. I wonder if Coop disburses the money through CAF and the beneficiary numbers are CAF account numbers? It would seem bizarre but I have come to expect bizarre.

**Comment by stevieflow** [comment]
Actions

Consider if CAF should be an entry in org-id.  @Julianlstar did you find out any more?

Also - then consider what / where this fits into documentation

**Comment by Julianlstar** [comment]
I did enquire but got nowhere. I am will ask again though as Coop seem to have ground to a halt in the data release process

Julian

Julian Tait
Project Lead - Greater Manchester Pilot
Tel. +44 (0)7802 851 394
Skype: julianlstar
 
Read more about us <http://www.threesixtygiving.org/about/> and sign up to our newsletter here <http://www.threesixtygiving.org/contact/>.

**Comment by morchickit** [comment]
This should be looked at identifiers work. Tagging @drkane and closing this.
