### ISSUE TITLE
Include link to Data Quality Tool

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#207]
@morchickit also for you to consider - a link from http://standard.threesixtygiving.org/en/latest/ to https://dataquality.threesixtygiving.org/

Again - useful example is OCDS - http://standard.open-contracting.org/latest/en/ (link to Validator)

NB - Ill create a ticket for what we might want to do at the other end...

--> @Bjwebb

**Comment by caprenter** [comment]
For some reason this is in the Separate Documentation milestone. It should not be. So removing it from the milestone.

**Comment by BobHarper1** [comment]
I'd reason just sticking this under Useful Links?

**Comment by stevieflow** [comment]
@morchickit ?

**Comment by morchickit** [comment]
Sorry, missed this notification in my inbox!
I think this is something for @KDuerden to also decide since she is the one who mostly refers users to the quality tool. 
I think it's fine to link her but I want to see what Katherine thinks

**Comment by KDuerden** [comment]
Yes, that's a good idea, thank you. Data Quality Tool with link to https://dataquality.threesixtygiving.org/

**Comment by BobHarper1** [comment]
Version here http://standard.threesixtygiving.org/en/207-link-to-360cove/

**Comment by KDuerden** [comment]
Perfect. Happy for that to go live when you're ready.

**Comment by BobHarper1** [comment]
Yay, quickest ever?
