### ISSUE TITLE
REV identifiers are marked as charity numbers

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/standard#208]
Connected to #201 and flagged by @Julianlstar , we have around 1,400 cases where charities recorded REV numbers as charity numbers, giving them the wrong identifier. While this is less than 1% of the whole database, it is easy to fix and feed back to publishers. 

Most of these are from the BLF and recorded as NIC (95%), but others are recording this as well . For the sake of better quality - should we ask publishers to fix it, giving it the right identifier? Why are we even the option to record REV when the REV dataset is closed (and probably should stay closed)?  We have 90 of those in the system, which is nothing, but still need to clarify that this is not a good identifier (all of these are from the Dulverton trust - cc @KDuerden) 

I can link to the file if it's useful

**Comment by Julianlstar** [comment]
This issue came up with the Coop who have a variety of REV numbers. The pragmatic decision has been to dump them as they themselves are a concerned about them being in the public domain as there is a remote possibility they could be maliciously used.

**Comment by stevieflow** [comment]
I dont think these are "wrong" identifiers.  GB-REV is legitimate for certain cases afaik: http://org-id.guide/list/GB-REV

**Comment by timgdavies** [comment]
Agreed. These are relevant identifiers of the charitable status of unincorporated organisations.

I'm not sure of the abuse potential of these being in the public domain: any more context on that?

**Comment by Julianlstar** [comment]
There are two issues that have cropped up whilst looking into this. First is that Coop were uncomfortable with these numbers as they aren't in the public domain and their maybe a remote possibility of their abuse. They themselves see them as being pretty useless as they can't be used to validate an organisation with the HMRC - apparently they have tried and the numbers have to be taken on trust.
Secondly whilst seeing what other publishers are doing with them I found that a few organisations are wrongly assigning them to the the Northern Ireland Charity register with GB-NIC-XR123456 Big Lottery are two.

**Comment by KDuerden** [comment]
I am not aware of any cases of misuse, and all the publishers I have worked with who have these numbers did not have any reservations. I would be know of some examples, so I can help publishers assess the risks. Obviously Coop can make their own judgement about using the IDs in their data.

Revenue numbers used to be the only number possible for NI charities, and these are often displayed on their own websites and these are common currency as identifiers for unregistered charities - eg funders ask for them / charities offer them when asked to provide a charity number.

The process of phasing NI charities into the Charity Commission for Northern Ireland register (with 6 digit number starting 1) is supposed to take over a decade so these will be around for a while yet. 

I'm not too concerned by wrong prefixes, as we can feedback to the orgs to update (fwi Esmee's org IDs are a work in progress anyway). Although not public domain, as these are genuine unique IDs for orgs (albeit taken on trust), then the chances of finding a connection through these ID does exist, whereas there is no chance with internal IDs.

**Comment by KDuerden** [comment]
@morchickit Regarding Dulverton Trust, I can investigate. They use Salesforce and so this particular issue looks like it could be a problem with their Org ID formula.

**Comment by stevieflow** [comment]
Thanks @KDuerden 

I'd suggest we close this issue.  It is not an issue with the standard

Also:

> REV identifiers are marked as charity numbers

This is misleading.  No ``Recipient Org: Identifier`` has any mark or signifier

**Comment by morchickit** [comment]
Re-opening please since I see no where else where we can speak about identifier, which are part of our standard. Until we have a forum, I dont see where else we can discuss this. 

Let me re-write this so it will be clearer:

1. We have organisations that use REV number as NIC numbers, even though the organisations are not in NI. 
2. We have REV numbers to charities in NI that has charities numbers. 

If we do use XR numbers because of the reasons above, than this has to be signposted to the data users. I am aware that this is know to you since you are working on this project since it started, but It is currently not written anywhere, and since we dont have a full dataset of REV numbers, users should be aware of this and understand it, even if it's 1% of the data.

**Comment by stevieflow** [comment]
OK- @morchickit take a look at http://threesixtygiving-standard.readthedocs.io/en/revisions-for-usability/identifiers/#organisation-identifier - this is some revised documentation guidance around identifiers, in a branch we are waiting to merge.  Maybe there is opportunity to add some specific GB-REV guidance here -- @KDuerden ?

**Comment by morchickit** [comment]
@stevieflow let me open a specific issue on the REV number and documentation.

**Comment by stevieflow** [comment]
> @stevieflow let me open a specific issue on the REV number and documentation.

https://github.com/ThreeSixtyGiving/standard/issues/211

**Comment by stevieflow** [comment]
Action: build on http://threesixtygiving-standard.readthedocs.io/en/revisions-for-usability/identifiers/ to make reference to this

**Comment by stevieflow** [comment]
Closing as --> #211
