### ISSUE TITLE
Amending already published grants

### ISSUE THREAD

**Issue by prbass** [ThreeSixtyGiving/standard#21]
Query from a publisher (Nesta):

"the final amount of funding awarded at the end of the contract will fairly often be different from what we originally committed to – I have had a question from the guys working on our data here – how will  publication best work to allow us to amend award amounts after reconciling our budget?"

I'm guessing the answer to this is to re-publish the same row with an updated "Last modified" date, and an amended "Total amount awarded"

The best way to do it might be to add "transactions" showing the original amount awarded, and then the +ve or -ve adjustment with the appropriate date. 

This begs the further question - what is the relationship between "Total amount awarded"  "Total amount applied for" in the activity block, and any applicationTransaction, disbursementTransaction, commitmentTransaction 

E.g.. is it a problem is the sum of all of the commitmentTransactions != "Total amount awarded"

**Comment by practicalparticipation** [comment]
I've added an 'amountDisbursed' top-level property, so there is a match between the 'Application', 'Award' and 'Disbursement' types of transaction that can be recorded in detailed transaction tables. 

In previous version of the standard, TotalAmountAwarded was supposed to be auto-generated from 'Award' transactions (and same for TotalApplicationValue), but in updated version I propose we make this stand-alone properties. 

Publishers should keep them consistent, but tooling working with the standard will not be required to perform the aggregation (though they may wish to check consistency of these two ways of expressing amounts)

**Comment by morchickit** [comment]
@KDuerden - this is an old issue, what is our guidance to this now? I want to move it to the forum and wanted to know what is your answer to this first.

**Comment by morchickit** [comment]
@KDuerden  ping

**Comment by KDuerden** [comment]
Yes, this comes up a lot. Can you give me a bit of time to consolidate the info, before moving anything to the forum on this.

**Comment by morchickit** [comment]
Sure. I will ping you again after the new year :-)

**Comment by morchickit** [comment]
@KDuerden - pinging. :-)

**Comment by mariongalley** [comment]
This is fixed, and there is publicly available guidance on [amending existing data](https://standard.threesixtygiving.org/en/latest/guidance/making-updates/#making-changes-to-your-published-data)
