### ISSUE TITLE
Add REV prefix to the documentation 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/standard#211]
Expalin in the documentation what is REV and when it is used in 360Giving data (NI example)

**Comment by stevieflow** [comment]
I'd advise that we get http://threesixtygiving-standard.readthedocs.io/en/revisions-for-usability/identifiers/#organisation-identifier merged to live first (once @KDuerden has approved).  The REV guidance can be the next iteration.

**Comment by morchickit** [comment]
Agreed on the path forward. Just wanted to add it here so we won't forget.

**Comment by stevieflow** [comment]
> Agreed on the path forward. Just wanted to add it here so we won't forget.

:+1:

**Comment by morchickit** [comment]
This is now in the documentation. Closing this!
