### ISSUE TITLE
Proposal: explicit date-time format for 'Last Modified'

### ISSUE THREAD

**Issue by BobHarper1** [ThreeSixtyGiving/standard#218]
### Proposal
An update to the documentation (including description in the schema) to be explicit that dates in the `Last Modified` group are formatted as:

> Year-month-day 'the letter T' hour:minute:second Timezone

`yyyy-mm-ddThh:mm:ss<timezone>`

`<timezone>` should be replaced with:
'Z' for UTC, or
±hh:mm for timezones other than UTC

e.g. _2017-10-18T15:01:23Z_

### Why make this change?
360Giving markers for change (the `Last Modified` group of fields) provides publishers with a way of signalling to users when information has changed. This is important for systems which aggregate data from multiple sources on a regular basis. It will allow them to know when they need to update their copy of a dataset, and when the data is unchanged.

Currently, the schema expects a `date-time` which has a [specific meaning](https://tools.ietf.org/html/rfc3339#section-5.6) in [JSON Schema](http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.1), but there is no explicit information on what a date-time should look like in either the documentation or the schema descriptions. This can cause confusion for publishers when they publish their grants information, users checking if the dates are accurate and developers creating validators based on the schema.

Using full timestamps removes any ambiguity that can occur when, for example, a record is updated in a source system multiple times in a single day. Without a full timestamp, there is a risk that systems with overwrite newer data with older data.

### Impact
This is not a change as such, but is an area where there has been some confusion and some difficulty to comply. Publishers should check that they are complying with this requirement of the standard and seek help if they need it.

Data users should already be expecting to receive date-time data in these fields. This change should not affect them unless they have been taking steps to deal with non-compliant data in these fields.

You can feedback to this discussion in the topic on the [360 Giving Community Forum](https://forum.threesixtygiving.org/t/proposals-for-change-date-formats/46).

**Comment by stevieflow** [comment]
As per https://github.com/ThreeSixtyGiving/standard/issues/63 - ``Last modified``title should soon be ``Last Modified``

**Comment by stevieflow** [comment]
Just to clarify - I think a lot of publishers will just use date - eg YYYY-MM-DD in this field already, in line with other date fields.  If we do this, will they suddenly become invalid (and not get into GN!)?  I dont think so, but want to check -- > @Bjwebb

**Comment by morchickit** [comment]
Isn't this discussion should be in the forum?

**Comment by BobHarper1** [comment]
@stevieflow Thanks, I've changed that in the title

@morchickit I've [posted in the forum](https://forum.threesixtygiving.org/t/proposals-for-change-date-formats/46). I think they can exist as three separate issues here, but we can have a discussion around the changes as one topic (as they are closely related) in the forum. Tell me if I'm wrong about that!

**Comment by morchickit** [comment]
Making total sense Bob!

**Comment by morchickit** [comment]
Ok, so looking at @stevieflow comment, I think we just need to see if it will make older entries invalid, but even if so, surely we can provide publishers with an easy way to fix it (ie, excel format).

**Comment by BobHarper1** [comment]
@morchickit Just to update you on this, we do have an examples box under the field guidance on how to do dates and times right in Excel in this version of the Documentation.  http://standard.threesixtygiving.org/en/date-validation/reference/#dates-and-times

I think we're aware of all of the publishers who need to make these changes, and we'll do another check before implementing them to the live schema.

**Comment by BobHarper1** [comment]
I'm just noticing that we also have titles 

- ["Transaction date"](https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L27)
- ["Value date"](https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L43)
- ["From an open call?"](https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L551)

Since we know that case changes have no effect, should we go ahead any make them consistent? @stevieflow @morchickit ?

**Comment by stevieflow** [comment]
Good spot @BobHarper1 

> Since we know that case changes have no effect

If that is the case, then I see no harm.....

**Comment by morchickit** [comment]
Agree with Steven. Let's go with this.

**Comment by BobHarper1** [comment]
Added to the pull request https://github.com/ThreeSixtyGiving/standard/pull/221

**Comment by stevieflow** [comment]
https://github.com/ThreeSixtyGiving/standard/pull/221 was merged and deployed on Feb 1 2018
