### ISSUE TITLE
Proposal: explicit date or date-time in known date fields

### ISSUE THREAD

**Issue by BobHarper1** [ThreeSixtyGiving/standard#219]
### Proposal
An update to the documentation (including description in the schema) to be explicit that **known dates** are formatted as **either one of**:

> Full year-month-day 'the letter T' hour:minute:second Timezone

`yyyy-mm-ddThh:mm:ss<timezone>`

`<timezone>` should be replaced with:
'Z' for UTC, or
±hh:mm for timezones other than UTC

e.g. _2017-10-18T15:01:23Z_

**OR**:

> Full year-month-day

`yyyy-mm-dd`

e.g. _2017-10-18_

Publishers will therefore had the choice of using either `yyyy-mm-ddThh:mm:ss<timezone>` or `yyyy-mm-dd` formats for this group of dates.

### Why make this change?
This group of dates (known dates, e.g. 'Award Date') provides publishers with a way of providing known dates to users. These are dates where it is important to know the exact day, but the time of day is not necessarily important.

Currently, the schema expects a date-time but documentation states:
> “Dates should be in YYYY-MM-DD format”. 

This causes confusion for publishers when they publish their grants information, users checking if the dates are accurate, and developers creating validators based on the schema.

Using full timestamps removes any ambiguity that can occur when, for example, a record is updated in a source system multiple times in a single day. Without a full timestamp, there is a risk that systems with overwrite newer data with older data.

### Impact
This will require a change to the JSON schema. Anyone relying on the current version of the schema will be affected. However, any effects are likely to be small, as the change is only about how dates may be formatted. Anyone following the schema would have allowed date-times, this will still be allowed, but they will now also be able to allow the shortened date format as well.

Publishers should check that they are complying with this requirement of the standard and seek help if they need it.

You can feedback to this discussion in the topic on the [360 Giving Community Forum](https://forum.threesixtygiving.org/t/proposals-for-change-date-formats/46).

**Comment by Racheler** [comment]
I'm not clear from this thread if we are proposing the use of either of these options, or just the first option (with a full time stamp including the time zone). Please clarify. Thanks.

Also, if this is a change to the JSON schema, I assume it will affect just those publishers? (There are currently two that use the JSON schema rather than Excel.) If so, will their data still be valid?

**Comment by BobHarper1** [comment]
It's a case of being able to use either of those formats: either just the full date, or the full date plus time and zone. I've made that clearer in the proposal text.

It would also affect Excel datasets as they will be validated in the same manner as any JSON (or csv) file would be _against_ the Schema (@stevieflow?)

**Comment by morchickit** [comment]
I was thinking about it, why do we need specific time for awarding grant? The data is important, but the the time itself can be random for some publishers, no? Is this just to make it more in line?

**Comment by BobHarper1** [comment]
It doesn't need a specific time, it could just be a date with no time. It would seem odd that anyone would need to supply or want a time, but if a datetime is used, we also need to make sure that it's not treated as invalid

**Comment by stevieflow** [comment]
Checking in on the situation for this we have the following in the schema for ``awardDate``:

> When was the decision to award this grant made. The date should be written as YYYY-MM-DD, or in full date-time format.

Similarly to #220 this seems to address the original proposal.  

--> @Bjwebb @morchickit @KDuerden

**Comment by Bjwebb** [comment]
Yes, I think this issue is now done.
