### ISSUE TITLE
Codelist for Organisation Type

### ISSUE THREAD

**Issue by practicalparticipation** [ThreeSixtyGiving/standard#23]
We should provide a controlled codelist for organisation type.

Suggested values:
- Registered Charity
- Registered Company
- ???

**Comment by timgdavies** [comment]
I'm not sure that this has been important so far - so suggest leaving this on the backlog unless @ekoner @stevieflow have experience that suggests we should prioritise it.

**Comment by morchickit** [comment]
We will start by asking in the forum more general questions:

1Do we want to start to use codelists? If so which fields? How we will introduce it? 

According to the response we can start working on this issue.

**Comment by suninthesky** [comment]
This would be very useful for Beehive. @drkane explored it a little...

_in a private repo so screenshotting_
![screen shot 2017-09-07 at 11 40 09](https://user-images.githubusercontent.com/7393302/30159707-7379ec06-93c1-11e7-9b88-52ed25dc9c03.png)

**Comment by morchickit** [comment]
See forum discussion here: https://forum.threesixtygiving.org/t/codelists-and-360giving-standard/20 

I am keeping this issue open for now.
