### ISSUE TITLE
Should master branch be protected with 'Review required' for PRs?

### ISSUE THREAD

**Issue by edugomez** [ThreeSixtyGiving/standard#235]

**Comment by Bjwebb** [comment]
@stevieflow @BobHarper1 What do you think to this?

**Comment by BobHarper1** [comment]
It's sensible to do this in the way we already work, without direct commits to master and a period of review before merging.

**Comment by stevieflow** [comment]
Yes,  I think

**Comment by Bjwebb** [comment]
I've added this.
