### ISSUE TITLE
Duration (months) - "or an end date"

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#240]
Whilst looking into https://github.com/ThreeSixtyGiving/standard/pull/238

> Events or activities lasting more than one day should have either a duration (in months) or an end date.

@morchickit @KDuerden - Im guessing we dont really want/need a *date* in this field?
@Bjwebb currently, is a date supported here - or is the description wrong?

**Comment by Bjwebb** [comment]
I think the description doesn't mean in this field (which isn't supported), but rather that you should have either "End Date" or "Duration (months). End Date has the same sentence in it: https://github.com/ThreeSixtyGiving/standard/issues/240

**Comment by stevieflow** [comment]
@morchickit @KDuerden  shall we edit this?

**Comment by KDuerden** [comment]
Yes. Not sure how best to explain weeks/partial months - any suggestions?

"Events or activities lasting more than one day should have a duration. Duration should be in months, in number format."

**Comment by morchickit** [comment]
Sounds good to me

**Comment by KDuerden** [comment]
+1

**Comment by stevieflow** [comment]
OK - have created a PR on this specifically.  I think the end date description would also need review/change.  Ill do similar

**Comment by stevieflow** [comment]
One thing to flag - we have the schema for the summary tables:

https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-summary-table-schema.json

@Bjwebb just double checking, but I should make a similar PR on that?

**Comment by Bjwebb** [comment]
Yes, I think so.

**Comment by stevieflow** [comment]
I think this now all in place
