### ISSUE TITLE
Planned End dates needs review

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#242]
Related to #240 the description text we hold in schema for End dates

Currently

> Events or activities lasting more than one day should have either a duration (in months) or an end date. Dates should be in YYYY-MM-DD or date-time format. If the month or day are not available, these may be omitted.

First proposal:

> An end date for the grant. Dates should be in YYYY-MM-DD or date-time format. If the month or day are not available, these may be omitted.

cc/ @Bjwebb @KDuerden

**Comment by morchickit** [comment]
Assigned to me to approve?

**Comment by stevieflow** [comment]
@morchickit sorry was just using assignee function to pass it onto you initially.  Just need feedback from you @KDuerden really!

**Comment by KDuerden** [comment]
Add in 'See the Date guidance for details' and link here? http://standard.threesixtygiving.org/en/latest/reference/#dates-and-times

**Comment by stevieflow** [comment]
@KDuerden I know it might be helpful, but I'd try to avoid adding in links to external resources (even though it's our own docs!) within the schema, just in case they change one day, for some reason.  It's a dependency  that can easily be forgotten, and then appear broken for a while

Sorry - I agree that that isn't a helpful suggestion from me!

**Comment by KDuerden** [comment]
So links are there to Org ID guidance because it is not external?
In that case can we still tell people to see the guidance. Then work out how to make the Date guidance more obvious!?

**Comment by stevieflow** [comment]
@KDuerden yes, good point

> So links are there to Org ID guidance because it is not external?

Although - if you do click on that link within the JSON schema box, we get into strange territory with documentation-within-documentaton: http://standard.threesixtygiving.org/en/latest/reference/#json-format !
> In that case can we still tell people to see the guidance sans link. Then work out how to make the Date guidance more obvious?

Yes, of course.  We can cite it , and then look to include such guidance as main links in the left hand side navigation?

**Comment by KDuerden** [comment]
Agreed. Update text first, then let's look for a home in the navigation.

**Comment by stevieflow** [comment]
Have created the PR for this description change. Also noting that I have this may need to happen in summary table schema --> @Bjwebb

**Comment by Bjwebb** [comment]
Yes, I think so.

**Comment by stevieflow** [comment]
I think this now all in place
