### ISSUE TITLE
Related Activity has a title but is missing from the docs

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#249]
The field [relatedActivity](https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L1290) has a title: 

```
    "relatedActivity": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "The identifiers of any related activities (e.g. other grants given as part of a multi-grant project)",
      "weight": 15,
      "title": "Related Activity"
```
However, this seems to be missing from the table summary, and so the docs: http://standard.threesixtygiving.org/en/latest/reference/#spreadsheet-format

cc/ @KDuerden

**Comment by timgdavies** [comment]
From a quick look, it appears this is the only `array` at the top level of the schema which only has strings as it's contents. I suspect that as a result the table generation process is missing it. 

I see it is appearing in the spreadsheet template, so I would suspect this is an issue with the Sphinx Directive. 

@bjwebb should be able to confirm that and identify a fix.
