### ISSUE TITLE
Finalise the descriptions of the metadata package 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/standard#251]
In this doc - https://docs.google.com/spreadsheets/d/1ZjsRkeRr44H1INMDpc4HgYpcB1WHxQg3Lqqmk8bpilE/edit?ts=5b6858cf#gid=0

**Comment by stevieflow** [comment]
This is linked to us seeing the documentation first of all --> #252

**Comment by stevieflow** [comment]
This has been done through work with the Stewardship Committee
