### ISSUE TITLE
Update the metadata branch 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/standard#252]
So the we can see the work on it and comment on it here.

**Comment by stevieflow** [comment]
This refers to us outputting the metada branch to http://standard.threesixtygiving.org/en/latest/ - so that we can work on the documentation

@Bjwebb @kindly I'm not exactly sure where or how this would appear, but can we push the metadata package to the docs?

**Comment by stevieflow** [comment]
Done: http://standard.threesixtygiving.org/en/package-metadata/
