### ISSUE TITLE
OrganisationType field: remove partial codelist

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/standard#255]
I got a feedback from the Challenge Fund that publishers dont use the Recipient Org:Organisation Type field and tried to understany why the Big Lottery created the field BIGField_Organisation_Type.

I asked Katherine about it, and she said it is a codelist. Digging into the documentation, you can see that the spreadsheet format doumentations says:

Recipient Org:Organisation Type | A description of this organisation | string | False

The JSON documentation however says the following:
organisationType | enum | string,null | Registered Charity Registered Company Community Group List to be updated

What does this means for version 1? Should we keep it as string, change to classification or expand this codelist?

**Comment by timgdavies** [comment]
I believe there was early on a desire for this information in cases where no organisation identifiers were supplied. But where we have good use of organisation identifiers, then some of this can be inferred. 

I don't have a strong opinion on whether to extend or remove the codelist. However, the field description probably needs to be updated, as this is not just a 'description of the organisation', but should be 'a description of the type of the organisation'.

**Comment by stevieflow** [comment]
Thanks @timgdavies 

@morchickit @KDuerden - what do you think?

**Comment by morchickit** [comment]
I think if we can make it a free text filed that would be the best option,
since we see that other organisations do want this field and use
alternative one (like the Big Lottery).

**Comment by KDuerden** [comment]
+1 for free text.

@stevieflow  no one has used this field (or the Funding Org Type equivalent) because the couple of times it seemed like a possibility including it rendered the data invalid because the values they wanted to use weren't on the list. In at least one case we just moved the text to the org description field because it is free-text.

**Comment by stevieflow** [comment]
OK thanks.  @morchickit I've create a new project for proposals for v1.1  - and added this to it

**Comment by morchickit** [comment]
We should then put it forward this issue forum as well for acknowledgement.
I'll do it today.

**Comment by drkane** [comment]
I've put down some thoughts in the forum - free text makes sense to me.

https://forum.threesixtygiving.org/t/recipient-organisation-type-field/255/2

**Comment by KDuerden** [comment]
@morchickit yes please - conversation last week with publisher I had to suggest an alternative field for data they have about type of org - because this is a codelist.

**Comment by stevieflow** [comment]
Have created a branch for this https://github.com/ThreeSixtyGiving/standard/tree/255-OrganisationTypeList

**Comment by KDuerden** [comment]
What's the eta on this branch being pushed to live? There is a publisher we want to move onto using this field rather than their own field title.

**Comment by robredpath** [comment]
@KDuerden this has now been merged to live

**Comment by morchickit** [comment]
Can we close this?

**Comment by robredpath** [comment]
@morchickit yup!

**Comment by KDuerden** [comment]
@robredpath I understood this change was live but CoVE is giving error messages for data using the field, sans codelist: https://dataquality.threesixtygiving.org/data/8399663a-a215-43df-a2bd-981e96754b92
This file hasn't been failing the daily data test, and has loaded into GN ok.

**Comment by stevieflow** [comment]
This error https://dataquality.threesixtygiving.org/data/8399663a-a215-43df-a2bd-981e96754b92 looks like a codelist is still being checked for / exists....

**Comment by robredpath** [comment]
I've got a PR open for this now - we accidentally pulled in a link to an old version of the schema when doing the metadata work

**Comment by robredpath** [comment]
https://github.com/OpenDataServices/cove/pull/1236

**Comment by KDuerden** [comment]
thanks @robredpath - thought it might be something like that!

**Comment by robredpath** [comment]
@stevieflow @KDuerden fixed now - you'll need to resubmit the data as validation results are cached, but that data now passes
