### ISSUE TITLE
Document mandatory fields

### ISSUE THREAD

**Issue by practicalparticipation** [ThreeSixtyGiving/standard#27]
We need to identify and document all mandatory fields in the standard.

**Comment by pmackay** [comment]
I notice the table schema (https://github.com/ThreeSixtyGiving/standard/blob/master/schema/summary-table/360-summary-table-schema.json) has `required` attributes but the JSON schema doesnt - would it be useful to transfer those across?

**Comment by practicalparticipation** [comment]
The JSON Schema at
https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json
does include required elements. Was there somewhere else where it has
fallen out of sync?



On Mon, Mar 16, 2015 at 8:48 AM, Paul Mackay <notifications@github.com>
wrote:

> I notice the table schema (
> https://github.com/ThreeSixtyGiving/standard/blob/master/schema/summary-table/360-summary-table-schema.json)
> has required attributes but the JSON schema doesnt - would it be useful
> to transfer those across?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/27#issuecomment-81509148>
> .
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by pmackay** [comment]
Ah, they're defined in separate arrays, was comparing where the required attribute is in each field object in the table schema. 

What is remaining to complete on this issue then?

**Comment by practicalparticipation** [comment]
I think this might be covered now. Will close it.

On Mon, Mar 16, 2015 at 8:39 PM, Paul Mackay <notifications@github.com>
wrote:

> Ah, they're defined in separate arrays, was comparing where the required
> attribute is in each field object in the table schema.
>
> What is remaining to complete on this issue then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/27#issuecomment-81925847>
> .
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.
