### ISSUE TITLE
How should ward or parliamentary constituency locations be published?

### ISSUE THREAD

**Issue by practicalparticipation** [ThreeSixtyGiving/standard#28]
We need to review, and better document, the way of publishing locations such as ward or constituency.

**Comment by practicalparticipation** [comment]
Related issue #29

**Comment by timgdavies** [comment]
This is now an issue of documentation.

**Comment by ekoner** [comment]
@timgdavies is this complete and ready to close?

**Comment by timgdavies** [comment]
Yes. We can re-open if future need for better geographic documentation.
