### ISSUE TITLE
URL in governance.md Footnote 4 gives 404

### ISSUE THREAD

**Issue by mrshll1001** [ThreeSixtyGiving/standard#280]
[Footnote 4 on governance.md](http://standard.threesixtygiving.org/en/latest/governance/#id9) lists http://cove.opendataservices.coop/360/ as the URL for more information however it returns 404.

If the linked page has been removed we can possibly link to http://cove.opendataservices.coop or https://dataquality.threesixtygiving.org/

**Comment by Bjwebb** [comment]
http://cove.opendataservices.coop/360/ is the old url for https://dataquality.threesixtygiving.org/, so I've set that to redirect. Probably best to update the docs to the new url though.

**Comment by robredpath** [comment]
I've suggested changing the footnote in the PR anyway

**Comment by mrshll1001** [comment]
I think this has been completed. There is currently no reference to http://cove.opendataservices.coop/360/ on the governance page on the live version of the standard.
