### ISSUE TITLE
Admin geography (for UK grants)

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#29]
It would be useful to declare the relevant admin geography/geographies that a grant benefits.  

This could be particularly useful for locally administered grants - which are ward (or even sub-ward - eg LSOA) specific. 

In terms of UK admin geo areas, then the GSS codes could be useful - as these can describe various levels (LSOA, Ward, District, and even Region): eg: http://statistics.data.gov.uk/doc/statistical-geography/E05000692

Additional administrative geographies do also exist - Clinical Commissioning Groups, for example (see grants data at https://www.manchestercommunitycentral.org/policy-and-influence/open-data).  These could (also) be declared through a code and a code-class ?

**Comment by stevieflow** [comment]
The OS ontology on admin geography is also a good reference point: http://data.ordnancesurvey.co.uk/ontology/admingeo/

**Comment by stevieflow** [comment]
Is it feasible to add to the ``beneficiaryLocation`` element:

``admingeoCode`` ``admingeoType``

This would enable a ward code and a Ward to then be declared...

We may then need to clarify and decribe the use case for this in relation to the other fields:

"name","countryCode","point"

**Comment by practicalparticipation** [comment]
Can you give an example of values for each of these? 

In the past we had thought that we might use the gazeteer for locations, but I think this might add too much complexity - so I think a flatter ```adminGeoCode``` and type makes sense - but assuming the 'type' is a codelist I'm wondering how we minimise our need to maintain codelists here....

**Comment by stevieflow** [comment]
Taking the Nesta office, and a lookup via MySociety:

http://mapit.mysociety.org/postcode/EC4A%201DE.html

Ward code is : E05009297 (the gss codes are preferable) 

LSOA code is: E01000004

With the Macc data, there is also Clinical Commissioning Groups (CCG) - lookup: http://www.england.nhs.uk/resources/ccg-directory/ (not part of 

Hence:

adminGeoCode: E05009297
adminGeoType: Ward

adminGeoCode: E01000004
adminGeoType: LSOA

adminGeoCode: 07T 
adminGeoType: CCG

NB: data doesnt have to be presented for all possible administrative geographies.  Publishers can obviously choose the level to which they would detail (or omit )

**Comment by practicalparticipation** [comment]
Ok. The other approach to consider (which is used in the LGA schemas at http://validator.opendata.esd.org.uk/publictoilets is to just go with a URL, and give guidance on which URLs to prefer).

However, assuming we go with the Code and Type options then we'll need to put together a brief code list which contains:

* Code
* Name
* Notes
* Lookup service

For each of the geographic gazeteers we want to encourage use of.

I'm just looking at whether the current Gazeteer section of the standard could be used for this, or whether just simplifying to the two properties of location makes the most sense (leaning towards later option).

**Comment by stevieflow** [comment]
Yes - simplification of the Location and Gazeteer section might be a good step.

One issue I can foresee is when somebody wishes to describe "other" - most commonly "UK wide" in terms of the beneficiary location.  Hence, it is great to describe the specific LSOA and/or Ward and/or District and/or CCG Area for a grant, but this is not always detailed.  By not including such geography are we to assume the grant is non-specified?  Or should something always be specified - which starts to bleed into mandatory field territory

**Comment by prbass** [comment]
Another snafu I've been dealing with today: neither the codes or the names
of gazetteer entries are persistent.

In 2013 they moved one house from Gateshead to Northumberland, or possibly
the other way round, and some cul-de-sacs from Hertfordshire to Stevenage
(or vice versa). All four areas got new codes, and the old codes
disappeared from the latest versions of ONS statistical releases (although
it is still possible to look them up in the gazetteer)

This broke one of NCVO's antiquated spreadsheets.

This probably means that this kind of geocoded information should also come
with a date.

**Comment by practicalparticipation** [comment]
I think we have to assume it is possible to leave this blank, and that would mean 'not specified'.

So we would need a suggested explicit way to code for UK-Wide (or even Europe Wide, or World Wide).

**Comment by stevieflow** [comment]
@prbass yes, understood.  Although - within 360 we could *assume* that the intended area to benefit from the grant would be at the time of the award - it would be highly unusual that a grant was awarded to a non-existent area.  In other words - we could use the plannedDates instead of a new date.

Of course areas do change, but between the OS and ONS, I think there is some changelog..:

http://data.ordnancesurvey.co.uk/doc/7000000000018770
http://statistics.data.gov.uk/doc/statistical-geography/E05000706


@practicalparticipation re: explicitly state highly level geographies.  Sticking within the same namespaces - we have:

http://data.ordnancesurvey.co.uk/doc/country/england
http://statistics.data.gov.uk/doc/statistical-geography/E92000001

but - perhaps a string/name will also do when it is beyond UK.. (and of course, country codes can be used)?

**Comment by practicalparticipation** [comment]
I've added geoCode and geoCodeType to the location element, and have removed the Gazetteer option for clarity.

Using the [ONS Linked Data Service](http://statistics.data.gov.uk/doc/statistical-entity/?_pageSize=50&_page=1&_view=full) I put together a [first shot at at codelist of geographic areas here](https://github.com/ThreeSixtyGiving/standard/blob/master/codelists/geoCodeType.csv). 

However, I fear this has:

(a) Duplication - I see 'WD' used as the abbreviation for a number of different ONS Codesets - so not sure the abbreviations are appropriate to use as our codes;

(b) Too much in it - but I wasn't sure how best to cull it down.

Also, the current links are just to example resources - as this was auto-generated. Ideally we would link to good search services for the most common codes people want to use.

@stevieflow Would you be able to have a shot at editing this codelist into something more useful for your needs.

**Comment by stevieflow** [comment]
Excellent - thanks @practicalparticipation 

So - are you OK if I edit this *down* to fewer items?

**Comment by practicalparticipation** [comment]
Absolutely. Remove anything you think not needed as easy to add back
later...

**Comment by timgdavies** [comment]
Closing this ticket. The management of the location codelist is a separate issue.
