### ISSUE TITLE
Include metadata spreadsheet template

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#293]
In the Meta sheet docs, create a link for the words "360Giving Spreadsheet Template with the Metadata template" to this file (centrally hosted on the github repo --> /assets ? )

[360-giving-schema-titles-with-meta-tab.xlsx](https://github.com/ThreeSixtyGiving/standard/files/6236998/360-giving-schema-titles-with-meta-tab.xlsx)

![360Giving-Data-Standard-documentation (3)](https://user-images.githubusercontent.com/1209944/113154299-cd468080-922f-11eb-827d-d28400050ac9.png)

**Comment by Bjwebb** [comment]
Done at https://standard.threesixtygiving.org/en/2021-package-metadata/reference/#meta-sheet
