### ISSUE TITLE
Provide data protection guidance in documentation

### ISSUE THREAD

**Issue by practicalparticipation** [ThreeSixtyGiving/standard#31]
We should provide some guidance in the documentation regarding data protection.

**Comment by stevieflow** [comment]
@ekoner any suggestions as to where we might point?

**Comment by ekoner** [comment]
We could signpost publishers to the ICO's [Anonymisation code of practice](https://ico.org.uk/for-organisations/guide-to-data-protection/anonymisation/) or to [UKAN](http://ukanon.net/) The UK Anonymisation Network who have an excellent range of [resources](http://ukanon.net/ukan-resources/)

**Comment by ekoner** [comment]
#130 pull request created

**Comment by stevieflow** [comment]
Closing, as the specific task was done.  We may revisit this in other iterations / new issues
