### ISSUE TITLE
Document Organisation ID standard

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#32]
In the documentation reference is made to:

> An organisation identifier, following the Organisation ID standard.

Is this available anywhere?

**Comment by practicalparticipation** [comment]
Not in the current 360Giving documentation - so this is definitely something we should add. 

I believe https://practicalparticipation.github.io/organisation-id-tool/ which I had planned to reference is also now running off an outdated copy of the codelist, so would be great for us to think about a small convenience tool to help people generate IDs too.

**Comment by practicalparticipation** [comment]
## Identifiers

### Activity Identifier

Every grant needs to have a stable, globally unique identifier (GUID). The basic idea of a GUID is that there should be no other grant in the world with the same ID. Whenever any two people encounter this ID in the context of grant making, they can be sure they are talking about the same grant. 

The easiest way to generate a stable GUID is to add a unique prefix onto the identifiers used in existing systems. For example:

>If the Apple Foundation have given their first grant of £1000 support a Llama farm and they call this ‘Grant1’ in their systems, and the Orange Foundation have given their first grant of £10m to support marine conversation research, and they also refer to this as ‘Grant1’, then if they both identify these as ‘Grant1’, any system working with the data might confuse these two. 
>
>However, if Apple Foundation register a 360 Giving prefix of ‘360G-Apple’ and the Orange Foundation register a 360 Giving prefix of ‘360G-Orange’ then they can assign the **public** identifiers of ‘360G-Apple-Grant1’ and ‘360G-Orange-Grant1’ respectively, helping computers to know that these are different grants.
>
>They can both keep using Grant1 as the identifier in their internal systems: they just need to add the prefix when publishing data. 

It is also important that the identifier for a grant does not change. If Apple foundation suddenly started referring to it’s Llama grant as ‘GRANT-LLAMA’ and published new files with the same information, but the ID ‘360G-Apple-GRANT-LLAMA’, then computers reading the data could double-count the grant, as they cannot tell that ‘360G-Apple-Grant1’ and ‘360G-Apple-GRANT-LLAMA’ are the same thing.

Registering a 360 Giving Prefix is the easiest way to get a stable globally unique identifier. 

Once you have registered your prefix then you can append onto it the grant activity identifiers from your internal system. 

If you do not already have identifiers for your grants, you should look to create these. You could use a numerical scheme (1, 2, 3, 4, 5 and so-on), or short alphanumeric codes (e.g. LLAMA). You should avoid long identifiers, and should not include spaces or special characters other than ```_``` and ```-``` in your identifiers.

#### IATI Publishers
If you are already publishing data to the International Aid Transparency Initiative standard then you can use your existing IATI Activity Identifier as a GUID. This is created by prefixing your own Organisation ID onto your internal identifier for the grant. Note that if your organisation ID changes (e.g. you register as a charity) then you should not change the prefix used for past grants, and should only use the new organisation identifier for future grants). 



### Organisation Identifiers
	
Finding out which organisations have received grants is an important part of the 360 Giving standard. 

For each organisation record you can provide:

* An organisation identifier
* A name
* An alternative name (e.g. trading as)
* A charity number (if applicable)
* A company number (if applicable)
* Address and website details

Often data publishers will have one or more of these bits of information, but they may not have all of them. The more information that is provided, the greater chance there is that we can identify and match together information about each organisation covered by 360 Giving data. 

The organisation identifier is a particularly important piece of information. Follow the steps below to work out what identifier to record for each Funding and Recipient organisation in your dataset.

**(1) Q: Is this grant to an individual, unregistered community group, or registered organisation (e.g. company, charity, educational institution)?**

A: Individual or unregistered community group

* Do you have an internal identifier in your systems for this grantee?
  * Yes: Prefix this internal identifier with your 360 Giving prefix, and then ‘-ORG-‘. For example, if Apple Foundation made a grant to ‘Peter Smith’ and had internally identified this grantee as ‘a12’ then they would use the Organisation ID: ‘360G-Apple-ORG-a12’ 
  * No: Use your 360 Giving prefix, plus ‘-ORG-individual’, ‘-ORG-group’, ‘ORG-charity’, ‘ORG-company’, ‘ORG-cic’ or ‘ORG-misc’ as the identifier. For example, if Orange Foundation made a grant to the ‘Bonn Brass Band’, but had not recorded any internal identifier for this group, they would use the ID: ‘360G-Orange-ORG-group’ Identifiers ending ‘-group’, ‘-individual’, ‘-company’, ‘-charity’,’-cic’ or ‘-misc’ should be recognised as special identifiers by consuming applications. 

A: Registered organisation:

* Have you recorded the registered identifier for this organisation? For example, their charity, company or education institution number?
  * Yes: You should lookup the prefix code [TODO – BUILD LOOKUP SERVICE] for the registered identifier you have, and append the identifier onto this.
  * No: Do you have an internal identifier in your system for this grantee?
    * Answers as above

**Comment by practicalparticipation** [comment]
## Identifiers

### Activity Identifier

Every grant needs to have a stable, globally unique identifier (GUID). The basic idea of a GUID is that there should be no other grant in the world with the same ID. Whenever any two people encounter this ID in the context of grant making, they can be sure they are talking about the same grant. 

The easiest way to generate a stable GUID is to add a unique prefix onto the identifiers used in existing systems. For example:

>If the Apple Foundation have given their first grant of £1000 support a Llama farm and they call this ‘Grant1’ in their systems, and the Orange Foundation have given their first grant of £10m to support marine conversation research, and they also refer to this as ‘Grant1’, then if they both identify these as ‘Grant1’, any system working with the data might confuse these two. 
>
>However, if Apple Foundation register a 360 Giving prefix of ‘360G-Apple’ and the Orange Foundation register a 360 Giving prefix of ‘360G-Orange’ then they can assign the **public** identifiers of ‘360G-Apple-Grant1’ and ‘360G-Orange-Grant1’ respectively, helping computers to know that these are different grants.
>
>They can both keep using Grant1 as the identifier in their internal systems: they just need to add the prefix when publishing data. 

It is also important that the identifier for a grant does not change. If Apple foundation suddenly started referring to it’s Llama grant as ‘GRANT-LLAMA’ and published new files with the same information, but the ID ‘360G-Apple-GRANT-LLAMA’, then computers reading the data could double-count the grant, as they cannot tell that ‘360G-Apple-Grant1’ and ‘360G-Apple-GRANT-LLAMA’ are the same thing.

Registering a 360 Giving Prefix is the easiest way to get a stable globally unique identifier. 

Once you have registered your prefix then you can append onto it the grant activity identifiers from your internal system. 

If you do not already have identifiers for your grants, you should look to create these. You could use a numerical scheme (1, 2, 3, 4, 5 and so-on), or short alphanumeric codes (e.g. LLAMA). You should avoid long identifiers, and should not include spaces or special characters other than ```_``` and ```-``` in your identifiers.

#### IATI Publishers
If you are already publishing data to the International Aid Transparency Initiative standard then you can use your existing IATI Activity Identifier as a GUID. This is created by prefixing your own Organisation ID onto your internal identifier for the grant. Note that if your organisation ID changes (e.g. you register as a charity) then you should not change the prefix used for past grants, and should only use the new organisation identifier for future grants). 



### Organisation Identifiers
	
Finding out which organisations have received grants is an important part of the 360 Giving standard. 

For each organisation record you can provide:

* An organisation identifier
* A name
* An alternative name (e.g. trading as)
* A charity number (if applicable)
* A company number (if applicable)
* Address and website details

Often data publishers will have one or more of these bits of information, but they may not have all of them. The more information that is provided, the greater chance there is that we can identify and match together information about each organisation covered by 360 Giving data. 

The organisation identifier is a particularly important piece of information. Follow the steps below to work out what identifier to record for each Funding and Recipient organisation in your dataset.

**(1) Q: Is this grant to an individual, unregistered community group, or registered organisation (e.g. company, charity, educational institution)?**

A: Individual or unregistered community group

* Do you have an internal identifier in your systems for this grantee?
  * Yes: Prefix this internal identifier with your 360 Giving prefix, and then ‘-ORG-‘. For example, if Apple Foundation made a grant to ‘Peter Smith’ and had internally identified this grantee as ‘a12’ then they would use the Organisation ID: ‘360G-Apple-ORG-a12’ 
  * No: Use your 360 Giving prefix, plus ‘-ORG-individual’, ‘-ORG-group’, ‘ORG-charity’, ‘ORG-company’, ‘ORG-cic’ or ‘ORG-misc’ as the identifier. For example, if Orange Foundation made a grant to the ‘Bonn Brass Band’, but had not recorded any internal identifier for this group, they would use the ID: ‘360G-Orange-ORG-group’ Identifiers ending ‘-group’, ‘-individual’, ‘-company’, ‘-charity’,’-cic’ or ‘-misc’ should be recognised as special identifiers by consuming applications. 

A: Registered organisation:

* Have you recorded the registered identifier for this organisation? For example, their charity, company or education institution number?
  * Yes: You should lookup the prefix code [TODO – BUILD LOOKUP SERVICE] for the registered identifier you have, and append the identifier onto this.
  * No: Do you have an internal identifier in your system for this grantee?
    * Answers as above

**Comment by timgdavies** [comment]
This is now in the docs.
