### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/standard#33]
Planed instead of Planned - https://github.com/ThreeSixtyGiving/standard/blob/6504bf5a76148f8e5f29e3e0e8cfd27f9fb54e07/schema/360-giving-schema.json#L525

In fact, this is overwriting an early definition of plannedDates:
https://github.com/ThreeSixtyGiving/standard/blob/6504bf5a76148f8e5f29e3e0e8cfd27f9fb54e07/schema/360-giving-schema.json#L491

**Comment by practicalparticipation** [comment]
Updated in https://github.com/ThreeSixtyGiving/standard/commit/9666b73a3d5351bc73ab9630310605d6d9e11fc1
