### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/standard#333]
On the [Community Foundations page](https://standard.threesixtygiving.org/en/latest/guidance/cf-guidance/), the [link to download guidance](https://standard.threesixtygiving.org/en/latest/assets/Data%20preparation%20guide%20for%20community%20foundations%20-%20PDF%20version.pdf) does not work.

What's the cause of the broken link and how can I fix it? Do I need to re-upload the guidance or is it stored somewhere still?

**Comment by mrshll1001** [comment]
Whoops! This slipped the net. @mariongalley I think this may be fixed now;

* https://www.threesixtygiving.org/wp-content/uploads/Data_preparation_guide_for_community_foundations-PDF_version.pdf

Can this be closed?

**Comment by mariongalley** [comment]
Yep, thanks @mrshll1001
