### ISSUE TITLE
Implementing actions from 2022-11 SC

### ISSUE THREAD

**Issue by mrshll1001** [ThreeSixtyGiving/standard#336]
Ticket to track discussions / implementation of actions from 2022-11 Stewardship Committee

**Comment by mrshll1001** [comment]
I've set up a branch 336-november-feature-update, for pushing and managing the changes to this branch and for allowing us to set up a CoVE for testing it.

Currently, I've pushed the `regrantType` field; it currently uses an embedded codelist (enum) in the schema but this should be changed to a CSV one at a later date when @Bjwebb has implemented that work.

**Comment by mariongalley** [comment]
@mrshll1001 I think this can be closed
