### ISSUE TITLE
Case sensitive field names

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#35]
Are field names case sensitive - eg `id` rather than `Id` ?  I'm guessing this is so - as laid out in the schema.  

There is a use case whereby if someone manually enters the field names into excel/calc, then the software will auto capitalise the first letter of the string (`id` to `Id`), which could cause problems....

**Comment by practicalparticipation** [comment]
Field names are generally case sensitive for most consuming apllications
*but* if in our tooling for the registry we are going to generate converted
copies of each sheet we could make our tools more forgiving and make the
validator WARN rather then throw errors on this.

That would shift more of the sorting data out labour onto users and lower
fiddly barriers to publishing.

Depends on how tricky we think some people would find it to correct those
headers and how supportive we can make the validator I think....

**Comment by timgdavies** [comment]
@Bjwebb @kindly Can you confirm what the position is now on case sensitivity with flattening tools?

I'm flagging this as an issue that should be clarified in updated documentation where I suggest:

* We say that the standard is case sensitive, and make sure documentation case is consistent;

but

* Our tools are more forgiving on case, perhaps raising warnings?

**Comment by Bjwebb** [comment]
Are tools treat field names as strictly cases sensitive, but all 360Giving spreadsheet users use titles, which are case insensitive.
