### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#36]
It would be useful to have the initial and new releases of the standard tagged - in order to provide documentation on the changes (for example)

**Comment by practicalparticipation** [comment]
In terms of tagged in GitHub? Or to have a version number for the standard baked into the data in some way?

**Comment by stevieflow** [comment]
as in: https://github.com/IATI/IATI-Schemas/releases ?
 
At this early stage, it might not be more than just pointing out where the versions are, rather than bake something into the data..

**Comment by practicalparticipation** [comment]
Ok - yes. As soon as we get to 1.0 let's start doing this.

**Comment by timgdavies** [comment]
We should do this as part of updating the schema.

**Comment by Bjwebb** [comment]
I'm not quite clear what the next tagged release will be. Have we reached 1.0, or are we still releasing RCs? https://github.com/ThreeSixtyGiving/standard/releases

**Comment by Bjwebb** [comment]
Actually, from reading https://github.com/ThreeSixtyGiving/standard/milestones/Revised%20Schema it looks like the plan is to have a formal 1.0 in September https://github.com/ThreeSixtyGiving/standard/milestones/3/edit

**Comment by stevieflow** [comment]
@Bjwebb is this a new plan / recently added by someone ( @timgdavies?)

**Comment by Bjwebb** [comment]
I assume so.

**Comment by stevieflow** [comment]
Updated this to add to the two GitHub projects that are around for 0.9 and 1.0 releases.  I assume we would use tagged releases for these

**Comment by stevieflow** [comment]
Update - we will tag initially at 1.0.

@morchickit keeping this issue open to ensure we do

**Comment by stevieflow** [comment]
We've done this for 1.0.0 https://github.com/ThreeSixtyGiving/standard/releases/tag/1.0.0
