### ISSUE TITLE
Mapping between initial and latest version

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#37]
Create a mapping file for changes field names

**Comment by practicalparticipation** [comment]
I'm working on the documentation for this at the moment - as I think I've left things a bit misleading in current draft templates. 

Essentially:

- Publishers can still use the 'Title' based column headings - and my sense is this is better for basic users;
- The flatten-ocds tool (which we need to create a forked & renamed version of) can now handle this when converting to JSON;

This means there are in theory quite a few different serializations of 360 Giving data model now (Summary table / Multi-table / JSON - and - field names or field titles) - but I think we need to focus on supporting a minimum number of these.

Here's draft docs. I'll get updated templates uploaded shortly:

## 360 Giving Formats
You can choose from three formats for publishing your data: 

1.	Summary spreadsheet: provided with user-friendly field names, and for recording one grant per row. This is the most common template that publishers choose. CSV | Excel | Documentation

2.	Multi-table data package (under development): for when you have more in-depth information to share, such as the location of multiple beneficiary groups, or detailed payments schedules. Provided with machine-readable field names.  Get in touch 

3.	JSON Schema: for providing a structured representation of your data direct from your internal databases or via an API. Ideal for direct use by developers building visualisations and web apps. Schema

The ‘360 Bridge’ tool will convert between each of these template formats, providing structured data for developers, and spreadsheet simplicity if you want to browse, sort and filter data on your desktop.

**Comment by practicalparticipation** [comment]
Here's a more detailed draft section of documentation which might help. Feedback and questions welcome:


## Data model & serialisation
The 360 Giving standard is defined by a JSON Schema. This describes the key entities that can be described using the standard, and the properties recognised by the standard. 

At the root of the data model is a grant-making Activity. Activities have a number of direct properties (e.g. Title, Description, Currency, Amount Awarded etc.) and then a number of related entities, including Organisations (Funder and Recipient), Locations (Recipient, Beneficiary), Classifications, Grant Programmes, and Transactions. 

The JSON Schema is the authoritative source of information about the standard, and it should always be possible to transform 360 Giving data into structured JSON data according to this schema. 

### Flattened & summary formats
To make it possible to work with 360 Giving data in everyday desktop tools, such as Excel or OpenOffice Calc, the standard provides a number of flattened serializations. These are created using the ‘360 bridge’ tool. 

### Basic flat template
The basic flat template (to be provided as a data package [coming soon]) provides an Activity table, and creates a table for each of the key entities in the standard, including extra columns in these tables for:

•	The ID of the Activity that the row describes;
•	The relationship that the row describes (e.g. in the Organisation table, whether the row describes a Funding or Recipient organisation)

In most cases, the entry in the relevant relationship column can be ‘1’. When there are one-to-many relationships represented (e.g. multiple classifications for a single activity), then the value in the relationship column should identify the position of the particular classification in the one-to-many sequence. 

TODO: WORKED EXAMPLE HERE

TODO: To generate a flattened template

TODO: To convert a flattened template

### Summary table
In many cases, publishers have data that can be expressed in a single abbreviated table row. This is generally the case when:

•	They do not have any one-to-many relationships in the data;
•	They do not have data to provide detailed descriptions of every element that the 360 Giving standard requires;

For this use case we provide a summary table. This summary table ‘rolls up’ properties of entities into the main Activity table, allowing information such as the recipient organisation address, beneficiary locations and grant programme details all to be given in the single row. 

For example, the structure:

* Activity
**recipientOrganization
*** Name

Can by represented in the Activity table under the column name:

```recipientOrganization[]/name``` or the column title (see below) ```Recipient Org:Name```. 

The default summary table template (with a selection of related entity properties brought into the Activity table) is defined by use of ‘rollUp’ properties in the JSON Schema file. However, it is possible, following the same naming convention for fields, to bring most properties into the Activity table if a particular use-case requires.

The naming convention for field names is to:

•	If the relationship can be a one-to-many relationship, append ```[]``` to the relationship property name 
•	Concatenate the relationship and property names using /
•	If required, indicate the type of the column values using the ```:number```, ```:integer```, ```:string```, ```:date-time``` and so-on.

The naming convention for field titles is to:

•	Concatenate the relationship and property titles using :

In the event that a value for a property is given in both a sub-table, and the summary table, the sub-table value always takes precedence, and will over-write the summary value. 

### Field names and titles
Each entity, property and relationship in the schema has both a machine-readable field name and an English language title.

The English language titles are important for humans working to make sense of the data in everyday desktop software, and so the default Summary Template makes use of titles as opposed to field names.

This could also support provision of the template in other languages in future. 

It is possible to map between titles and field names using the information in the JSON Schema. 

TODO: Also provide JSON TABLE SCHEMA FOR EACH OF THE SUB-TABLES
