### ISSUE TITLE
Split point location into separate latitude and longitude fields

### ISSUE THREAD

**Issue by practicalparticipation** [ThreeSixtyGiving/standard#38]
At the moment the standard includes point locations in a single lat-lng comma separated field.

This does not work with the standard configuration of tools like Recline.js and other mapping tools which assume separate latitude and longitude fields.

The original use of a composite field was based on [point in IATI](http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/location/point/) but we've diverged from this by having comma rather than space separated elements.

The suggestion is we split into separate lat and lng fields for the 1.0 standard.

This will affect a small number of existing publishers. 

@stevieflow your comments would be particularly useful on this.

**Comment by stevieflow** [comment]
From a data collection / management point of view (those people collating spreadsheets) then having these values in separate cells makes more sense, it seems.
