### ISSUE TITLE
Grant identifier - internal

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#41]
Should there be a field for organisations to maintain the identifier of the records, alongside the 360G-namespace identifier?

EG:

I am Organisation ABCD
I publish grant 11AA

I'd like to maintain 11AA in my dataset, as it is useful for internal records and use.  Therefore, I would publish

Grant:
Identifier: 360G-abcd-11AA
Internal Identifier: 11AA

(NB: this is similar to the ``other-identifier`` in IATI)

**Comment by practicalparticipation** [comment]
As this should be possible to derive trivially from the 360 Giving ID, and as we allow new columns to be added if people have extra data they want to store in their files, I'm not sure there is a strong case for including this as part of the standard.

**Comment by stevieflow** [comment]
OK , agree
