### ISSUE TITLE
Grant frequency

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#42]
I noticed from the Trafford data that there is a field ``Frequency Period``.  All values are "Single Award"  = but there might be worth a consideration around whether grants are single, multiple or ongoing

(more of an observation rather than a proposal)

**Comment by practicalparticipation** [comment]
Let's look out for other instances where this would be useful in future. There is a 'related grant' property which could be used to chain together a set of grants that repeat year-by-year - but I think in 360 Giving data we would want to encourage people to create a record for each time the grant is 'given', even if it is recurring in some form.

**Comment by stevieflow** [comment]
OK, agreed
