### ISSUE TITLE
Spreadsheet templates - Activity sheet

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#45]
Would it be more sense to rename the main sheets from Activity to Grants ?

**Comment by pmackay** [comment]
+1 - think this was discussed a bit at Nesta? Sounds clearer to me...

**Comment by practicalparticipation** [comment]
The original reason for this was so that the standard can also be used to capture non-Grant type information in future. Discussions in #26 on capturing social investments suggest that this might still be relevant.
