### ISSUE TITLE
Spreadsheet templates - ocid field

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#46]
Is there a mix up with OCDS in the tabs/sheets in the data templates?  There are labelled as ``ocid``, which I assume is "Open Contracting ID"?

**Comment by stevieflow** [comment]
eg: https://github.com/ThreeSixtyGiving/standard/blob/master/schema/summary-table/360-giving-schema-titles.csv/Location.csv

**Comment by practicalparticipation** [comment]
Yes - this is a bug in the template generation. Will look into it...

**Comment by practicalparticipation** [comment]
Need to discuss with @bjwebb and fix by end of week.

**Comment by Bjwebb** [comment]
Thanks for pointing this out for me, I've discussed this issue with @stevieflow separately, hadn't realised it affected this repo. Basically
