### ISSUE TITLE
Develop validation tool for CSV files

### ISSUE THREAD

**Issue by pmackay** [ThreeSixtyGiving/standard#47]
@practicalparticipation at the Nesta meeting you mentioned some tooling used in Open Contracting - what is the status of that? Could you add a bit more detail here? 

thanks!

**Comment by practicalparticipation** [comment]
The flattening-ocds tool is updated to work with 360 Giving Data. There are
some docs linked to here http://docs.threesixtygiving.org/tools/ but lots
more to be written up. @stevieflow has been testing out processes for
converting from spreadsheet->JSON etc.

@bjwebb will hopefully soon be working on renaming this tool, and then
we'll look at getting a webservice version of it.

Plans for the validator still to be worked out: aware we could validate
against JSON table schema right now for CSV files I believe, but we would
need to do more work for a good general purpose validator which can accept
spreadsheets or CSV and work things out.

All the best

Tim

On Mon, Mar 16, 2015 at 8:47 AM, Paul Mackay <notifications@github.com>
wrote:

> @practicalparticipation <https://github.com/practicalparticipation> at
> the Nesta meeting you mentioned some tooling used in Open Contracting -
> what is the status of that? Could you add a bit more detail here?
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/47>.
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by stevieflow** [comment]
Are we some way towards this with http://cove.opendataservices.coop/360/ now?  Perhaps this issue can be closed and specific issues posted at https://github.com/OpenDataServices/cove/issues ?

**Comment by Bjwebb** [comment]
We're some way towards this, but we don't quite have validation against the schema yet in Cove. The key outstanding issues are https://github.com/OpenDataServices/cove/issues/68 and https://github.com/OpenDataServices/cove/issues/46

**Comment by caprenter** [comment]
The issue referred to above have been closed now, and there is further progress on [CoVE]( http://cove.opendataservices.coop/360/).

CoVE validates by converting csv to json and then validating against the JSON schema. 

It might be worth keeping this issue around as validating other fortmats directly might be an idea worth holding onto.

**Comment by timgdavies** [comment]
@Bjwebb @kindly Can you update on whether we now have better direct CSV validation with the updated flatten tool and CoVE setup?

**Comment by stevieflow** [comment]
Belatedly closing this, as we have CSV validation in place via http://cove.opendataservices.coop/360/ (and have for a while)
