### ISSUE TITLE
Highlight required fields more

### ISSUE THREAD

**Issue by pmackay** [ThreeSixtyGiving/standard#48]
Just noticed that the column title/field name table on http://docs.threesixtygiving.org/docs/ is not that obvious showing which fields are required. What about to add a column saying if required or not? Happy to update and send a PR.

**Comment by practicalparticipation** [comment]
Sounds good - if you want to add that and PR that would be great.

On Mon, Mar 16, 2015 at 9:29 AM, Paul Mackay <notifications@github.com>
wrote:

> Just noticed that the column title/ field name table on
> http://docs.threesixtygiving.org/docs/ is not that obvious showing which
> fields are required. What about to add a column saying if required or not?
> Happy to update and send a PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/48>.
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by pmackay** [comment]
https://github.com/ThreeSixtyGiving/threesixtygiving.github.io/pull/1 created.
