### ISSUE TITLE
Consider UKPRN for university identification

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#49]
The UKPRN dataset may be appropriate to construct identifiers for UK Universities and Colleges:

https://www.hesa.ac.uk/kisdata (a spreadsheet can be downloaded)

It is maintained by the UKRLP: https://www.ukrlp.co.uk/

Should we propose this to IATI also?

**Comment by practicalparticipation** [comment]
Definitely worth proposing to the IATI processes - as we'll keep deferring
to that as much as we can.


On Mon, Mar 16, 2015 at 10:33 AM, Steven Flower <notifications@github.com>
wrote:

> The UKPRN dataset may be appropriate to construct identifiers for UK
> Universities and Colleges:
>
> https://www.hesa.ac.uk/kisdata (a spreadsheet can be downloaded)
>
> It is maintained by the UKRLP: https://www.ukrlp.co.uk/
>
> Should we propose this to IATI also?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/49>.
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by stevieflow** [comment]
Have posted : http://support.iatistandard.org/entries/80561095-Uk-Universities-Colleges-and-learning-providers-add-GB-UKPRN-as-RegistrationAgency

**Comment by practicalparticipation** [comment]
Great. Thanks :)

On Mon, Mar 16, 2015 at 11:00 AM, Steven Flower <notifications@github.com>
wrote:

> Have posted :
> http://support.iatistandard.org/entries/80561095-Uk-Universities-Colleges-and-learning-providers-add-GB-UKPRN-as-RegistrationAgency
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/49#issuecomment-81580723>
> .
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by stevieflow** [comment]
This was added to the IATI codelist: https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/59
