### ISSUE TITLE
Applicant Name(s)

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#50]
Observed from the Wellcome Trust data:
- Surname of applicant
- Full name of applicant
- Co-applicant

These are named individuals.  There is no capacity to record these in the standard as it stands

**Comment by practicalparticipation** [comment]
Related to #51 

In 360 Giving we assume recipient is an Organisation, but the full specification of 'Organisation' (see the [JSON Schema view here](http://docs.threesixtygiving.org/docs/) or the [table headings here](https://github.com/ThreeSixtyGiving/standard/blob/master/schema/summary-table/360-giving-schema-titles.csv/Organization.csv)) does include:

* Contact Name

This could at least be used I would think in research grants contact for the Surname and Full name of the applicant. 

However, it would not capture the co-applicant. If 360 Giving was going to be extended to work for a wide range of research grants (not sure this is a core use-case right now), then we might want to include space for multiple 'Investigators' on a research project, and to think about including space for their ORCHID identifiers (http://orcid.org/), but I think this would have to wait for a future iteration of the standard (do open an issue and we can add a 1.1 Milestone to it if you think this is important).

**Comment by morchickit** [comment]
See forum topic -https://forum.threesixtygiving.org/t/the-standard-doesnt-support-grants-for-individual-academic-work/22
Closing this so we can discuss it in the forum.
