### ISSUE TITLE
Recipient Org : Department

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#52]
As many Wellcome Trust grants go to universities, a column is included for ``Department``.  This is missing from the current standard (although ``Funding Org: Department`` was recently added)

**Comment by practicalparticipation** [comment]
You can add 'Recipient Org: Department' into the sheet - this is just not
in the template roll-up.

I believe at the moment the scripts might not convert this properly, but
need to discuss with @bjwebb whether the converter should accept this even
if schema does not state these properties are rolled up.

On Mon, Mar 16, 2015 at 11:07 AM, Steven Flower <notifications@github.com>
wrote:

> As many Wellcome Trust grants go to universities, a column is included for
> Department. This is missing from the current standard (although Funding
> Org: Department was recently added)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/52>.
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by stevieflow** [comment]
@bjwebb @caprenter I think this is still an issue.  Correct?

**Comment by Bjwebb** [comment]
@stevieflow Yes. Relevant flatten-tool issue is https://github.com/OpenDataServices/flatten-tool/issues/50 . We hope to look at this in the next couple of weeks.

**Comment by Bjwebb** [comment]
The rollup titles bug is now fixed in flattentool, see the commits against https://github.com/OpenDataServices/flatten-tool/issues/50 . This is now available for testing at http://flatten-tool-updates.dev.cove.opendataservices.coop/360/
