### ISSUE TITLE
Grant Type / Category

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#53]
Observed via Wellcome Trust data that a type/category is assigned to grants:

eg:

![image](https://cloud.githubusercontent.com/assets/1209944/6665052/059196f8-cbcd-11e4-8688-aada8da46d19.png)

This could be similar to `Grant Programme`, but also different.  This may also relate to #26 around the proposal of `Award Type`.

**Comment by practicalparticipation** [comment]
The way to do this right now would be using the Classifications table (once
we have #46 fixed) with a Vocabulary of '360-wellcome-type' and then the
values suggested.


On Mon, Mar 16, 2015 at 11:11 AM, Steven Flower <notifications@github.com>
wrote:

> Observed via Wellcome Trust data that a type/category is assigned to
> grants:
>
> eg:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1209944/6665052/059196f8-cbcd-11e4-8688-aada8da46d19.png>
>
> This could be similar to Grant Programme, but also different. This may
> also relate to #26
> <https://github.com/ThreeSixtyGiving/standard/issues/26> around the
> proposal of Award Type.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/53>.
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by stevieflow** [comment]
@timgdavies ok - have Classifications now been pushed into the documentation though: http://docs.threesixtygiving.org/docs/#toc5 ?

**Comment by ekoner** [comment]
Schema supports classification - closed.
