### ISSUE TITLE
Recipient Org: Address

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#54]
Currently, we only have:

Recipient Org:Street Address
Recipient Org:City

Is there a design reason for:
- No address details for Funding Org
- No option to insert address components such as Building, Town, etc

**Comment by practicalparticipation** [comment]
These do exist in the [full Organisation Specification](
https://github.com/ThreeSixtyGiving/standard/blob/master/schema/summary-table/360-giving-schema-titles.csv/Organization.csv).
I'd not included them in the 'roll up' summary as most incoming addresses
could not provide this level of detail... and to keep the number of fields
down, but perhaps we should have them in the roll-up.



On Mon, Mar 16, 2015 at 11:14 AM, Steven Flower <notifications@github.com>
wrote:

> Currently, we only have:
>
> Recipient Org:Street Address
> Recipient Org:City
>
> Is there a design reason for:
>
>    - No address details for Funding Org
>    - No option to insert address components such as Building, Town, etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/54>.
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by stevieflow** [comment]
I'm going to close this, as we know it is possible in the standard, and documentation support this: http://threesixtygiving-standard.readthedocs.io/en/revisions-for-usability/reference/#spreadsheet-format
