### ISSUE TITLE
Financial Year

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#55]
I observed that the DSDNI data only contained `Financial Year` as a date.  In processing to 360, the last date of each year was added.

Questions for the standard:
- Is `Financial Year` (eg: 2013-14) alone acceptable?
- Is it desirable to infer Financial Year when grant dates have been provided?

**Comment by practicalparticipation** [comment]
Good question. I think we would want to encourage any publishers to try and
provide an accurate date, or at least decide when data for a given
financial your should be 'booked' in terms of 360 Giving (i.e. they might
choose not to use the last day of year).

From a user perspective, having an inferred date makes a lot more sense
than leaving date blank.

We could introduce an additional 'Financial Year' property, but I'm not
sure what use-cases this would meet.



On Mon, Mar 16, 2015 at 11:16 AM, Steven Flower <notifications@github.com>
wrote:

> I observed that the DSDNI data only contained Financial Year as a date.
> In processing to 360, the last date of each year was added.
>
> Questions for the standard:
>
>    - Is Financial Year (eg: 2013-14) alone acceptable?
>    - Is it desirable to infer Financial Year when grant dates have been
>    provided?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/55>.
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by stevieflow** [comment]
Yes.  Knowing what financial year a grant falls within *could* be a useful addition to a dataset, but there is a risk of bloat.  Certainly, understanding the fiscal year dates of a funder could be helpful - although perhaps better recorded as metadata rather than per record/grant.

**Comment by stevieflow** [comment]
In Arts Council England data, there is ``Decision quarter``, which is a variation on this.  There is also a ``Award Date``, so such periods could be inferred

**Comment by stevieflow** [comment]
Two years later... we've seen adoption of ``awardDate`` across publishers, so this observation - whilst remaining true - doesn't seem to be a live request of the standard, or an important discussion to have.

We also know that in GrantNav, we've used the ``awardDate`` to create a year facet

Closing
