### ISSUE TITLE
Grant Status

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#56]
Observed via the DSDNI data - the field `Grant Status` exists, with values:

Grant approved
Letter of Offer Accepted
Letter of Offer Issued
Revised Letter of Offer Accepted
Revised Letter of Offer Issued

Alongside other data items related to the categorisation of grants (#53 #26) this might be worth investigation

**Comment by stevieflow** [comment]
Duplicate / related to #10

**Comment by ekoner** [comment]
Should also consider SORP requirements here

**Comment by stevieflow** [comment]
Closing - taking comment into #10
