### ISSUE TITLE
Funding Org : Branch

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#57]
Observed from the DSDNI data that there is a `Branch` alongside the organisation and department

For large organisations this might be relevant - but could also be too much

**Comment by practicalparticipation** [comment]
One option would be to broaden the definition of Department to 'Department
or Branch', and suggest that where both are present, they are separated by
a comma. I'm hesitant to include another field that might see very little
use.... but perhaps there are use-cases for having both?


On Mon, Mar 16, 2015 at 11:22 AM, Steven Flower <notifications@github.com>
wrote:

> Observed from the DSDNI data that there is a Branch alongside the
> organisation and department
>
> For large organisations this might be relevant - but could also be too
> much
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/standard/issues/57>.
>



-- 


w: http://www.timdavies.org.uk | m: 07834 856 303 | twitter: timdavies

Co-director of Practical Participation:
http://www.practicalparticipation.co.uk
--------------------------
Practical Participation Ltd is a registered company in England and Wales -
#5381958.

**Comment by morchickit** [comment]
The schema is now update and looking at sub-department: 

Funding Org:Department | The department or sub-unit of this organisation making or receiving the grant.

This therefore can be closed.
