### ISSUE TITLE
How to handle referred grants?

### ISSUE THREAD

**Issue by pmackay** [ThreeSixtyGiving/standard#60]
What is the best way to represent a grant where the finance is provided by organisation A, but the management of the grant is handled by organisation B?

**Comment by ekoner** [comment]
This is the situation at Oxford Community Foundation (OCF) where grants are funded by individuals and disbursed by OCF. This ties into proposals to distinguish between funder and publisher. Will look into this as part of the review.

**Comment by ekoner** [comment]
There was a suggestion to have a concept similar to Donor. Linking to #176 and #127

**Comment by stevieflow** [comment]
#176 is a fuller consideration of this issue.  @morchickit will move that to the forum, so closing this specific issue
