### ISSUE TITLE
How to handle joint grants?

### ISSUE THREAD

**Issue by pmackay** [ThreeSixtyGiving/standard#61]
Sometimes a grant can come from 2 organisations or two different departments, pooling to create a single pot. How to best represent this? 

Would be good to capture guidelines in the docs on this and #60.

**Comment by morchickit** [comment]
@KDuerden any insights here before I am moving it to the forum?

**Comment by morchickit** [comment]
@KDuerden  ping :-)

**Comment by KDuerden** [comment]
Joint grant is not a term I'm familiar with. If this is pooled funds then that it is re-granting with two or more source funders - and should sit with any discussion of that. I would think a solution to represent re-granting which allows for a reference to related grants/activities, would help link up contributors to a shared pot.

**Comment by morchickit** [comment]
@KDuerden - should we move this to the forum or close this?

**Comment by mariongalley** [comment]
This is fixed by #339 which covers a new Regranting field and codelist, with the option to specify Pooled funds
