### ISSUE TITLE
Percentage splits

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/standard#62]
It is possible for example to split a grant over 2 or more locations.

While all the locations can be reported, there is no way to say that 80% of the grant has gone to one location and 20% to the other for example.

Should the standard  make provision to do this?

**Comment by timgdavies** [comment]
## Proposal
I would suggest introduction of two new properties:

* ```percentFundsAtLocation```
* ```percentBeneficiariesAtLocation```

With the validation rule:

* For any type of location (either lat,lng, or any particular ```geoCodeType```) the total of each of ```percentFundsAtLocation``` and ```percentBeneficiariesAtLocation``` should be either 100, or 0 (i.e. the property is not used against this location type).
 
Would this cover what is needed?

Can you think of better names for these properties?

## Implementation
This could be implemented fairly easily in the location block of the schema, except that locations can be both:

* Organization/location
* Activity/beneficiaryLocation

It only appears to make sense to have percentages on beneficiaryLocation, although our current model for flattening doesn't work terribly well with this (location is a re-used block).

We could:

* Allow only a one-to-one relationship between Organization and it's Location, leading to location being flattened into the Organization table;

* Set the schema to create different BeneficiaryLocation and OrganizationLocation sub-tables

* Accept that there will be ```percentFundsAtLocation``` and ```percentBeneficiariesAtLocation``` showing in the schema for Organization, but note that these are not required and not meaningful in this case. 

Thoughts on the best option?

**Comment by morchickit** [comment]
This two years old and we haven't seen any evidence for this but we will move it to the forum and see and find use cases for it.

**Comment by morchickit** [comment]
See forum topic - https://forum.threesixtygiving.org/t/do-we-want-to-add-percentage-splits-of-location-to-grants/23

Closing this so the discussion can continue in the forum.
