### ISSUE TITLE
Titles cases e.g. Last modified vs Last Modified

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#63]
In the documentation, we cite `Last modified`, whereas other fields seems to have a capitalisation (eg: `Data Source`)

Therefore, suggest the schema:

> "title": "Last modified"

is changed to

> "title": "Last Modified"

**Comment by ekoner** [comment]
Title is still "Last modified" in the current schema - removed the `1 - Ready` label.

**Comment by stevieflow** [comment]
What would happen to data that currently has "Last Modified" as the title?  Will it be invalid?  We might want to build in something to accommodate this change, and not make it a - potentially - breaking one?

**Comment by Bjwebb** [comment]
@stevieflow flatten-tool treats this as case insensitive, so it isn't a problem for us (ie. CoVE, GrantNav etc.)

Should also be a fairly straightforward change for anyone else using the spreadsheets.

**Comment by BobHarper1** [comment]
FWIW, I've just checked this on CoVE with the current Arcadia dataset (capitalising **M**odified, so sort of the reverse of whenever these changes are affected), no issues https://dataquality.threesixtygiving.org/data/5d6eb446-221a-4eee-aeac-2ccd106706e9

**Comment by BobHarper1** [comment]
Changes the title for this issue as we also discovered:

- ["Transaction date"](https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L27)
- ["Value date"](https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L43)
- ["From an open call?"](https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L551)

So these field titles have also been updated to match the convention.
