### ISSUE TITLE
CSV /  Excel template - Sheet1 / Activity sheets

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#64]
This is also discussed in https://github.com/ThreeSixtyGiving/standard/issues/45 - but I wanted to raise a new issue in relation to the CoVE tool. 

@Bjwebb would we have a problem if the templates provided at http://docs.threesixtygiving.org/publish/ do not have sheets named as "grants"?

**Comment by Bjwebb** [comment]
Yes.

**Comment by stevieflow** [comment]
@timgdavies should we resolve this?

**Comment by timgdavies** [comment]
The updated template should now have a 'grants' root table.

@Bjwebb Does the capitalisation of this matter? (It would be nice if I could make it 'Grants' rather than 'grants')

**Comment by Bjwebb** [comment]
Capitalisation of this currently still matters. I think it probably makes sense to be case insensitive when using titles, including the sheet names (including this one) - there's an issue for this at https://github.com/OpenDataServices/cove/issues/94

**Comment by stevieflow** [comment]
Agreed  - that this should / could be Grants and not grants

**Comment by Bjwebb** [comment]
The new issue for case insensitivity is https://github.com/OpenDataServices/cove/issues/148

A guess a separate question is whether the template spreadsheet should have "Grants" or "grants" (if the former this would require modification to flatten-tool to generate it this way.

**Comment by stevieflow** [comment]
One thing to note, is that I've found it quite difficult for people to have the sheet named "grants" (or "Grants", or anything specific) when saving as csv

**Comment by Bjwebb** [comment]
@stevieflow Does the name of the sheet matter when saving as CSV?

**Comment by stevieflow** [comment]
@bjwebb for current CoVE behaviour, it does?

**Comment by Bjwebb** [comment]
@stevieflow It matters for XLSX. CSVs don't have sheet names (only filenames, nad CoVE doesn't care what the filename of a CSV is)...

**Comment by stevieflow** [comment]
@Bjwebb  I think I was thrown by this dataset: http://www.wolfson.org.uk/media/2723/wolfson-foundation-grants-2014.csv - which doesnt "work" in CoVE.  If you download it, and then change the sheet name to "grants", it is then parsed... but this might be mixing issues up

**Comment by Bjwebb** [comment]
@stevieflow Changing the sheet name will do nothing, it's not stored in a CSV. The problem with that file is encodings (which you may possibly fix just by opening it up and saving it again).

**Comment by Bjwebb** [comment]
I've moved the development issue for case insensitivity into the flatten-tool repo (rather than CoVE) https://github.com/OpenDataServices/flatten-tool/issues/75

**Comment by Bjwebb** [comment]
The dev copy of Cove now has case insensitive title headings, and main sheet names (e.g. 'grants' vs. 'Grants') is now fixed: http://dev.cove.opendataservices.coop/360/

The names of other sheets aren't yet case insensitive, as this is more difficult: https://github.com/OpenDataServices/flatten-tool/issues/75#issuecomment-173247934

Not sure if this issue can now be closed. We may want to document this better also.

**Comment by stevieflow** [comment]
Thanks @Bjwebb 

I cant see any mention of this at http://www.threesixtygiving.org/standard/ - or elsewhere, so not sure we need to actively document this.  @caprenter ?

**Comment by stevieflow** [comment]
Closing

Reopen if you see otherwise
