### ISSUE TITLE
Field name: Planned Dates:Duration (months)

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#65]
The (months) aspect of this name seems to stand out as a different label to all others.  Is it needed within the label?

However, the description does not then explain 

> Events or activities lasting more than one day should have either a duration (in days) or an end date.

Suggestion: remove (months) from label and adjust description to 

>  Planned number of months of the grant.  NB: Events or activities lasting more than one day should have either a duration (in days) or an end date.

**Comment by timgdavies** [comment]
The 'in days' was the incorrect part of the documentation. I have edited that, but kept the title the same (with (in months)) so as not to break any existing published data.

**Comment by caprenter** [comment]
For ref. This change was made in 33b12f9c1fd19b7f2c1400b2
