### ISSUE TITLE
360 Giving is now 360Giving

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/standard#68]
My understanding is that 360Giving is the preferred way of talking about it.

The documentation contains many instances of '360 Giving'

@stevieflow @timgdavies just checking with you that we should be changing that...

**Comment by stevieflow** [comment]
I didnt know that

**Comment by timgdavies** [comment]
You are right, and we should be changing it. Do you want me to look at that next week, or are you happy to pull a copy of the docs and edit?

**Comment by caprenter** [comment]
My plan would be to sed it, and check it via a diff.

@stevieflow has suggested a number of bug fixes, so I think the thing to do is bundle them all up and deploy on Monday

I'm happy to do all of this.

**Comment by timgdavies** [comment]
Great. Thanks.

**Comment by caprenter** [comment]
@stevieflow I know this because of: https://github.com/ThreeSixtyGiving/website/issues/7
The document in question is:
360 Website Text - 2015

**Comment by caprenter** [comment]
I've fixed this, and it is now deployed live

**Comment by caprenter** [comment]
@Bjwebb has pointed out that when I made the commit above I just did a find and replace without regenerating the documentation correctly, so I'm re-opening this, as this problem will now have re-emerged following: https://github.com/ThreeSixtyGiving/standard/pull/80

**Comment by caprenter** [comment]
This can be closed now and new issues can be reported if found
