### ISSUE TITLE
Classifications and Results

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/standard#71]
In the future we will want to look at common ways of representing grant classifications and results.

This issue is here to log discussions around this.

**Comment by timgdavies** [comment]
IRIS - from the Global Impact Investing Network (GIIN) have a library of metric indicators at https://iris.thegiin.org/metrics which are widely used - and may be a useful reference point.

**Comment by morchickit** [comment]
@timgdavies I want to move it to the forum, and we will have a discussion about code lists first. Anything concrete I can move to the forum or can we close this?

**Comment by morchickit** [comment]
@timgdavies  - ping!

**Comment by morchickit** [comment]
@timgdavies  - for the third time, is this still relevant? 
cc @stevieflow

**Comment by stevieflow** [comment]
It's just something that may or may not be discussed by the community in the forum.  It doesnt need action imho
