### ISSUE TITLE
Link in README to the documentation is broken

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/standard#76]
http://threesixtygiving.github.io/

Do we know if there should be a redirect in place for this, or should we just update to the new URL?

**Comment by timgdavies** [comment]
Lets update to the new URL. 

We could also add a redirect. 123-Reg account details for 360Giving are in our password vault account.

**Comment by caprenter** [comment]
The link is fixed in the README with the commit above.

I don't understand how the redirect works tho. 
http://threesixtygiving.github.io/ takes me to http://docs.threesixtygiving.org/standard - so I'm not sure where that redirect is made. 

Also, do we need the gh-pages branch any more?

**Comment by timgdavies** [comment]
The redirect at http://threesixtygiving.github.io/ will be configured on the gh-pages branch (possibly a meta-refresh tag?).

**Comment by timgdavies** [comment]
If we have no incoming links left to http://threesixtygiving.github.io/ and can't find anyone linking there, then it can be retired I think.

**Comment by caprenter** [comment]
I can't see anything obvious, nor am I sure how to see if there are incoming links.

So fixing the redirect still exists as a task, but in terms of the branch, if it's no longer used, but we're not sure about retiring it, could I request an update to the README:
https://github.com/ThreeSixtyGiving/standard/tree/gh-pages

**Comment by caprenter** [comment]
I've updated the message at the top of the http://threesixtygiving.github.io/ repository. I don't see any more references to the URL in README docs, so I'm pretty sure this is enough to now close this ticket.
