### ISSUE TITLE
Review mapping between 360Giving and SORP 

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/standard#77]
§16.13 - 16.25 of the [Statement of Reporting Principles for charities](http://www.charitiessorp.org/media/619092/frsse_complete.pdf) sets out the requirement for charities to report grants information in their accounts, and allows that:

> This information must be provided in the notes to the accounts, or by providing details of the charity’s webpage URL at which this information can be accessed, or this information may be set out within the trustees' annual report.

We should check that 360Giving contains all the information required to meet with SORP requirements. This might require us to create some validation rules around:
- Does a file capture giving for a particular year;
- Does the file capture purpose categories;

**Comment by ekoner** [comment]
[Mapping Charity SORP to 360Giving (England, Wales, Scotland)](https://docs.google.com/a/opendataservices.coop/spreadsheets/d/1Ezkz0pZozX2TUGRuMW19yjyUADADz8uyLcWJZ0SMWac/edit?usp=sharing) - document created. Closing issue.
