### ISSUE TITLE
sync-schema script should be deterministic

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/standard#78]
ie. given the same input it should produce the same output.

This is not currently true because JSON output of dictionaries is random by default.

If the output is deterministic, we would be able to write tests that check that everything is in sync.

**Comment by Bjwebb** [comment]
I've suggested a commit so the schema is deterministic.

XLSX files are still regenerated each time, but we can't meaningfully diff those anyway, so I think those are much lowere priority.

**Comment by caprenter** [comment]
This fix has been accepted, so closing this issue

**Comment by Bjwebb** [comment]
Outputted XLSX files are still not deterministic. Would be a nice to have to make diffs and pull requests easier if nothing esle.

**Comment by ekoner** [comment]
@Bjwebb can this be re-closed?

**Comment by Bjwebb** [comment]
Yes, sync-schema.sh is gone now.
