### ISSUE TITLE
Schema and generated documentation are out of sync

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/standard#79]
Specifically, this commit https://github.com/ThreeSixtyGiving/standard/commit/ef118304fcac8d5690073217cb5bc487853d3c04 changes "Three Sixty" -> ThreeSixty in docs generated from the schema, but not in the schema itself.

The two should be in sync, so I think the options are:
1) Change the schema.
2) Run the sync script, and undo some of the changes made in that commit.

**Comment by caprenter** [comment]
We can close this as the fix above has been merged
