### ISSUE TITLE
"fullscreen here" link doesn't work for me

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/standard#81]
On http://www.threesixtygiving.org/standard/reference/#toc-json-data-model

I'm on coffeeshop wifi, so possible it's an artefact of that, but I don't think so. Will double check in a bit.

**Comment by Bjwebb** [comment]
Looks like this was previously reported as part of https://github.com/ThreeSixtyGiving/website/issues/56

**Comment by caprenter** [comment]
This fix is in the master branch now, so will be fixed on the website next time we deploy
