### ISSUE TITLE
Better document what to do in this repo when changes are made

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/standard#85]
I'm still slightly confused about what to do here in this repo when I make changes to things.

So the README tells me to:
"After any changes to 360-giving-schema.json the sync_schema.sh script should be run to:

Generate CSV and XLSX templates
Update the documentation"

However, I think there may be other occasions when this needs to be run - e.g. if documentation is updated.

Today I was instructed to make changes to a file in https://github.com/ThreeSixtyGiving/standard/blob/master/documentation/src/reference.md
and then I would also need to run the sync_schema.sh script 

So I think the readme could perhaps do with a review. I think @Bjwebb has a good grip on this

**Comment by Bjwebb** [comment]
Yes, after updating the src documentation that script should also be run.

Will review the REAMDE as you suggest.
