### ISSUE TITLE
Should we alter the schema to check for Title length?

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/standard#97]
The title must not be more than 140 characters according to: http://www.threesixtygiving.org/standard/reference/

Can this be added to the schema and implemented in CoVE?

**Comment by caprenter** [comment]
While technically, I believe we could add this requirement to the schema, I'm not sure if this is something where we would actually want to be quite so strict. (See http://json-schema.org/latest/json-schema-validation.html#anchor26 )

So to be clear, the text "" is in the schema: https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L440
but there is no schema rule to enforce that at present.

We could therefore alter the schema to make it do so and to then throw a schema validation error, or we may want to leave the schema as it is, and not make the schema do any checking.

There will be ways for machines, software etc to check this requirement, by parsing the data and checking the length of titles to give warnings.  

I've created an issue for CoVE to look into this: https://github.com/OpenDataServices/cove/issues/201

**Comment by timgdavies** [comment]
I would suggest this should be handled as a 'warning' which CoVE and other tools flag, but not as a hard requirement of the schema. 

The reason for the 140 recommendation is to increase the tweet-ability of titles I think.

**Comment by ekoner** [comment]
Fixed in cove: https://github.com/OpenDataServices/cove/issues/201
